```{r packages}

library(ggplot2)

```



```{r loadData}

#Load all model outputs
data<-lapply(list.files("model-outputs/foraging/learning-evolution",full.names=T),read.csv)

#Rbind all CSVs together into one dataframe
data<-do.call("rbind",data)

```



```{r analysis}


#Create a dataframe for plotting average gamete size and fusion target over time
plotData<-data.frame("generation"=rep(sort(unique(data$generation)),length(unique(data$environmentPredict))*3))

plotData$strategy<-rep(c("Genetically Encoded","Model Free Learning","Model Based Learning"),each=length(unique(data$generation))*length(unique(data$environmentPredict)))
plotData$predict<-rep(sort(unique(data$environmentPredict)),each=length(unique(data$generation)),times=3)

plotData$mean<-c(sapply(0:2,function(x) c(tapply(data$learningGene1==x,list(data$generation,data$environmentPredict),mean))))

#Compute CIs on gamete sizes

plotData$lci<-c(sapply(0:2,function(x) c(tapply(data$learningGene1==x,list(data$generation,data$environmentPredict),function(y)
  mean(y)-sd(y)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)
  ))))

plotData$uci<-c(sapply(0:2,function(x) c(tapply(data$learningGene1==x,list(data$generation,data$environmentPredict),function(y)
  mean(y)+sd(y)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)
  ))))

plotData$lci[plotData$lci<0]<-0
plotData$uci[plotData$uci>1]<-1


plotData$predict<-factor(ifelse(plotData$predict==0,"Low Env. Predictability","High Env. Predictability"),levels=c("High Env. Predictability","Low Env. Predictability"))

```



```{r plot}

p1<-ggplot(data=plotData,
           aes(x=generation,y=mean,color=as.factor(strategy)))+
  geom_errorbar(aes(ymin=lci,ymax=uci))+
  labs(x="Generation",y="Proportion Agents\n w/ Learning Strategy",color="Learning Strategy")+
  facet_wrap(~predict)+
  scale_color_manual(values=c("dodgerblue3","firebrick3","orange"))+
  geom_point(size=2)+
  geom_line(linewidth=1)+
  coord_cartesian(ylim=c(0,1))+
  theme_grey(base_size=20)



```



```{r save}

ggsave("figures/MSAG Learning Evolution Figure (Pred 1).tiff",p0,width=12,height=6,units="in",dpi=300)
ggsave("figures/MSAG Learning Evolution Figure.tiff",p1,width=12,height=6,units="in",dpi=300)

```

