```{r packages}

library(ggplot2)

```



```{r loadData}

#Load all model outputs
data<-lapply(list.files("model-outputs/mating-strategy-nrb",full.names=T),read.csv)

#Rbind all CSVs together into one dataframe
data<-do.call("rbind",data)

#Classify gametes as big or small
data$bigOrSmall<-ifelse(data$gameteSizeGene1>3,"Large Gametes","Small Gametes")

```



```{r analysis}


#Create a dataframe for plotting mating-parenting tradeoffs, investment in competiton, and investment in parenting over time
plotData<-unique(data[,c(2,3,19)])

plotData<-plotData[order(plotData$bigOrSmall,plotData$generation),]

plotData$mpTradeoffMean<-c(tapply(data$mpTradeoffGene1,list(data$generation,data$bigOrSmall),mean))
plotData$competitionMean<-c(tapply(data$investCompetitionGene1,list(data$generation,data$bigOrSmall),mean))
plotData$parentingMean<-c(tapply(data$investParentingGene1,list(data$generation,data$bigOrSmall),mean))

#Compute CIs on mating-parenting tradeoff
plotData$tradeofflci<-c(tapply(data$mpTradeoffGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)-sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))
plotData$tradeoffuci<-c(tapply(data$mpTradeoffGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)+sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))

#Compute CIs on competition
plotData$competitionlci<-c(tapply(data$investCompetitionGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)-sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))
plotData$competitionuci<-c(tapply(data$investCompetitionGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)+sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))

#Compute CIs on parenting
plotData$parentinglci<-c(tapply(data$investParentingGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)-sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))
plotData$parentinguci<-c(tapply(data$investParentingGene1,list(data$generation,data$bigOrSmall),function(x) mean(x)+sd(x)/sqrt(max(data$modelLoop))*qt(.975,max(data$modelLoop)-1)))
```



```{r plot}

#Plot mating-parenting tradeoff over time as a function of gamete size and selection on parental investment
p1<-ggplot(data=plotData,
           aes(x=generation,y=mpTradeoffMean,color=as.factor(bigOrSmall)))+
  geom_errorbar(aes(ymin=tradeofflci,ymax=tradeoffuci))+
  labs(x="Generation",y="Mating-Parenting Tradeoff",color="Gamete Size")+
  scale_color_manual(values=c("orangered","steelblue"))+
  geom_point(size=2)+
  geom_line(linewidth=1)+
  coord_cartesian(ylim=c(0,1))+
  theme_grey(base_size=20)



#Plot investment in parenting over time as a function of gamete size and selection on parental investment
p2<-ggplot(data=plotData,
           aes(x=generation,y=parentingMean,color=as.factor(bigOrSmall)))+
  geom_errorbar(aes(ymin=parentinglci,ymax=parentinguci))+
  labs(x="Generation",y="Investment in Parenting",color="Gamete Size")+
  scale_color_manual(values=c("orangered","steelblue"))+
  geom_point(size=2)+
  geom_line(linewidth=1)+
  coord_cartesian(ylim=c(0,1))+
  theme_grey(base_size=20)



#Plot investment in competition over time as a function of gamete size and selection on parental investment
p3<-ggplot(data=plotData,
           aes(x=generation,y=competitionMean,color=as.factor(bigOrSmall)))+
  geom_errorbar(aes(ymin=competitionlci,ymax=competitionuci))+
  labs(x="Generation",y="Investment in Competition",color="Gamete Size")+
  scale_color_manual(values=c("orangered","steelblue"))+
  geom_point(size=2)+
  geom_line(linewidth=1)+
  coord_cartesian(ylim=c(0,1))+
  theme_grey(base_size=20)

```



```{r save}

ggsave("figures/MSAG NRB MP Tradeoff Figure.tiff",p1,width=12,height=6,units="in",dpi=300)

ggsave("figures/MSAG NRB Mating Strategy--Parenting Figure.tiff",p2,width=10,height=6,units="in",dpi=300)

ggsave("figures/MSAG NRB Mating Strategy--Competition Figure.tiff",p3,width=10,height=6,units="in",dpi=300)
```

