```{r packages}
library(doParallel)
```



```{r parameters}

#Populations#
#The number of agent populations (determined by prior simulation)
populations<-which(grepl("CHANGE LO",list.files("model-outputs/gender-evolution/",full.names=T)))



#Number of environments to simulate 
numEnv<-5



#Number of model loops
modelLoops<-length(populations)/numEnv



#Set desired population size
popSize <- 500



#Generations#
#Number of generations
generations<-20



#Mutation Rate#
mutationRate<-.05



#Selection Strength#
#Strength of selection on productivity
selStrength<-5



#Environment Predictability#
#How predictable the agent's natal environment will be
environmentPredict<-1



#Agent States#
#Create the set of possible states agents can be in
states<-c("parenting","successful","unsuccessful","injurySelf","injuryChild")



#Foraging Actions#
#Create the set of possible actions agents can take
actions<-c("parent",paste0("meat",1:5),paste0("plant",1:5))



#Lifespan#
#Number of learning trials agents experience
lifeSpan<-length(states)*length(actions)*10



#Learning Rate#
#Learning rate for Q-learning
learningRate<-.1



#Discount Rate#
#Discount rate for Q-learning
discount<-.9



#Epsilon#
#Initial epsilon for epislon greedy action selection
epsilon<-1



#Epsilon Decay Rate#
#How quickly epsilon decays with time
epsilonDecay<-1/lifeSpan



#Environmental Change#
#How likely ecological variables are to change each generation
envChange<-c(1,0)



#Observations#
#How many observations social learning agents have to pre-train their value functions
numObservations<-100

```



```{r functions}

#Agent Generation#
#Generate the agents
agentGenerate <- function(m, actions, states) {
  
  #Identify populations that will be used for this run
  pops<-(1:length(populations) %% modelLoops)==m

  #Load the agents
  agents<-lapply(list.files("model-outputs/gender-evolution",full.names=T)[which(grepl("CHANGE LO",list.files("model-outputs/gender-evolution",full.names=T)))][pops],read.csv)
  
  for(l in 1:length(agents)){
    #Limit to just the final generation of agents[[l]]
    agents[[l]]<-agents[[l]][agents[[l]]$generation==max(agents[[l]]$generation),]
    
    #Remove modelLoop, generation, and selection columns for now
    agents[[l]]<-agents[[l]][,-(1:3)]
    
    #Relabel rows
    row.names(agents[[l]])<-1:nrow(agents[[l]])
    
    #Limit to agents[[l]] that learn their foraging policy
    agents[[l]]<-agents[[l]][agents[[l]]$socialLearningGene1==2,]
    
    agents[[l]]<-agents[[l]][,1:19]
    
    #Create a gene reflecting whether agents police the policy of others
    agents[[l]]$policingGene1<-runif(nrow(agents[[l]]),0,1)
    agents[[l]]$policingGene2<-runif(nrow(agents[[l]]),0,1)
    
    #Create variables to keep track of agents' same-sex parents and their policing gene
    agents[[l]]$ssParentID<-0
    agents[[l]]$ssParentPolice<-0
  
    #Rearrange
    agents[[l]]<-agents[[l]][,c(1,22:23,2:10,20,11:19,21)]
    
    for(a in actions){
      agents[[l]]$x<-0
      
      colnames(agents[[l]])[ncol(agents[[l]])]<-paste0(a,"Hist")
      
    }
    
    #Store a reward value
    agents[[l]]$reward<-0
    
    #Create unique agent IDs
    agents[[l]]$ID<-paste0(l,"-",1:nrow(agents[[l]]))
  }
  
  
  
  #Initialize action value matrices for agents
  q <- lapply(1:length(agents),function(x)
              lapply(1:nrow(agents[[x]]), function(y)
    lapply(1:3, function(z)
      matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        )))
  )

  #Label action value matrices
  for(env in 1:length(agents)){
    names(q[[env]])<-agents[[env]]$ID
  }
  
  #Create matrices for learned theories about the optimal policy
  #Learned from social observations
  theories<-list(q,q)
  
  #Output agents
  return(list(agents,q, theories))
}



#Improved Sampling#
#A sample function that will return a scalar if provided
resample<-function(x,n){
  if(length(x)>1){
    return(sample(x,n))
  } else{
    return(x)
  }
}



#Action Selection#
#A function for selecting actions given agents' action-value functions and learning rule
actionSelection<-function(agents,q,parentQs){
  
  #Calculate probability of making an exploratory move
  epsilonProb<-max(c(.05, epsilon - epsilonDecay * l))
  
  #Loop through agents....
  chosenActions <- sapply(1:nrow(agents), function(x)
    
    #With probability proportional to parents' policing genes
    if((g > 1) & (rbinom(1,1,agents$ssParentPolice[x]))){
      #Either choose an action according to parents' policy
        actions[resample(which(parentQs[[as.character(agents$ssParentID[x])]][[agents$hhState[x]]][, agents$state[x]] ==
                                 max(parentQs[[as.character(agents$ssParentID[x])]][[agents$hhState[x]]][, agents$state[x]])), 1)]
    } else {
      #Or do epsilon greedy according to child's policy
      
      #On epsilonProb % of trials...
      if (rbinom(1, 1, epsilonProb)) {
        #Choose an action randomly
          sample(actions, 1)
        } else{
        #Or pick which ever action has maximum action value (ties broken randomly)
        actions[resample(which(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]] ==
                                 max(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]])), 1)]
      }
    }
  )
      
  #Output the actions
  return(chosenActions)
  
}



#Transition Matrix Setup
#A function to automatically generate transition matrices
#Creates a state transition matrix and a reward matrix
matrixSetup<-function(action, states, foragingVariables){
  
  #Action = action in question (parenting or a food)
  #States = possible agent stats
  #foraging Variables = variables about the foragable food items
  
  #If the action is parenting...
  if (action == "parent") {
    
    #Generate a blank matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    
    #Set transition to parenting to 1 for all starting states except states where agents are injured
    transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- 1
    
    #For states with injury, set transition to parenting to .8
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- .8
    
    #Set transition back to injury states to .2 for agents who start injured
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")), (colnames(transMatrix[[1]]) %in% c("injurySelf"))] <-
      .2
    
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")), (colnames(transMatrix[[1]]) %in% c("injuryChild"))] <-
      .2
    
    #Return of successful parenting is always 1
    transMatrix[[2]][, colnames(transMatrix[[2]]) == "parenting"]<-1

  } else {
    
    #For any food items...
    
    #Create a blank transition matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    #If the food item is risky (i.e. not guaranteed success)
    if(foragingVariables$risk[foragingVariables$foodItem==action]==1){
      
      #Set the probability of success
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- .5
      
      #Set the probability of failure
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- .5
      
      #If the agent is injured, decrease the probability of success by 80%
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))]<-
      (transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))])*.8
      
      #And set the probability of transitioning back to that injured state at .8
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")),
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")),
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.2
      
    } else {
      
      #If the food item is not risky (i.e. guaranteed success)...
      
      #Set the probability of success to 1
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- 1
      
      #And the probability of failure to 0
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- 0
      
      #Except if the agent is injured, then the probability of success is 80% and the probability of remaining in the injured state is 20%
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))]<-
      (transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))])*.8
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")),
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")),
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.2

    }
    
    #If the food item is dangerous (poses an injury risk)...
    if(foragingVariables$danger[foragingVariables$foodItem==action] == 1){
      
      #Set the probability of transitioning to the injured state to 10%
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "injurySelf"] <- .1
      
      #And decrease the probability of getting into the success states
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) !=
                           "injurySelf"] <- transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) !=
                           "injurySelf"]*.9
    }
    
    
    #If the foraging that food item is not compatible with child care...
    if (foragingVariables$childCompat[foragingVariables$foodItem==action] == 0) {
      
      #Set probability of injury to half the probability of succeeding or failing
      transMatrix[[1]][1, "injuryChild"] <- sum(transMatrix[[1]][1, c("successful", "unsuccessful")] *
                                                  .75)
      
      #And decrease the probability of succeeding or failing
      transMatrix[[1]][1, c("successful", "unsuccessful")] <- transMatrix[[1]][1, c("successful", "unsuccessful")] *
        .25
    }
    
    #Set the productivity of the food item
    #If the food item is productive, return 1/success rate (i.e., EV of foraging = 1),
    #Otherwise, set the expected value of foraging that food item to .5
    transMatrix[[2]][, "successful"] <- ifelse(foragingVariables$productivity[foragingVariables$foodItem ==
                                                                                action] == 1,
                                               1 / transMatrix[[1]]["successful", "successful"],
                                               .1 / transMatrix[[1]]["successful", "successful"])
    
  }

  #Output the transition matrix for this food item
  return(transMatrix)
  
}



#Environment Setup#
#A function to set up random environments
environmentSetup<-function(){
  
  #Create a dataframe reflecting the nature of foragable goods in this environment
  foragingVariables<-data.frame("foodItem"=actions[-1],
                                "productivity"=0,
                                "practice"=0,
                                "risk"=0,
                                "danger"=0,
                                "childCompat"=0)
  
  #Randomly generate an environment in which optimal foraging policy is either sex-differentiated or not
  if (rbinom(1, 1, .5)) {
    foragingVariables$productivity <- rep(c(1,rep(0,length(actions[-1])/2-1)),2)
    foragingVariables$practice <- rep(c(1,rep(0,length(actions[-1])/2-1)),2)
    foragingVariables$risk <- rep(c(1,0),each=length(actions[-1])/2)
    foragingVariables$danger <- c(1,rep(0,length(actions[-(1:2)])))
    foragingVariables$childCompat <- rep(c(0,1),each=length(actions[-1])/2)
  } else {
    foragingVariables$productivity <- rep(c(1,rep(0,length(actions[-1])/2-1)),2)
    foragingVariables$practice <- c(0,rep(0,length(actions[-(1:2)])))
    foragingVariables$risk <- rep(c(0,rep(1,length(actions[-1])/2-1)),2)
    foragingVariables$danger <- rep(c(0,rep(1,length(actions[-1])/2-1)),2)
    foragingVariables$childCompat <- rep(1,length(actions[-1]))
  }
  
  top<-head(1:nrow(foragingVariables),nrow(foragingVariables)/2)
  bottom<-tail(1:nrow(foragingVariables),nrow(foragingVariables)/2)
  
  #Randomly scramble the environment variables
  if(rbinom(1,1,.5)){
    foragingVariables[,-1]<-foragingVariables[c(bottom,top),-1]
  }

  foragingVariables[,-1]<-foragingVariables[c(sample(top),sample(bottom)),-1]


  #Generate transition matrices for this environment
  tMatrices <- lapply(actions, function(x)
    matrixSetup(x, states, foragingVariables))
  
  #Label appropriately
  names(tMatrices) <- actions
  
  return(list(foragingVariables,tMatrices))
  
}



#A function for executing transitions through the MDP given agents' actions
transitions<-function(agents,chosenActions,tMatrices){
  
  #Create a dataframe reflecting the result of each agent's action selection
  result<-data.frame("agentID"=agents$ID,
                     "hh"=agents$hh,
                     "startState"=agents$state,
                     "action"=chosenActions,
                     "newState"=rep(NA,nrow(agents)),
                     "yield"=NA)
  
    #Loop through agents
  for(a in 1:nrow(agents)){
    
    #Adjust agent state based on sex
    #Large gamete producers are treated as if they are in the parenting state with some probability
    #To represent minimum obligatory parental investment
    effectiveState<-ifelse(agents$gameteSizeGene1[a]<3,
                           agents$state[a],
                           ifelse(rbinom(1,1,.5),
                                  "parenting",
                                  agents$state[a]))
    
    #Determine the state transition
    result$newState[a]<-states[sample(1:length(states),
                               1,
                               prob=tMatrices[[chosenActions[a]]][[1]][effectiveState,])]
    
    #Determine yield of the agents' actions
    yield<-tMatrices[[chosenActions[a]]][[2]][effectiveState,result$newState[a]]
    
    #If the foraged good is practice-dependent, adjust yield based on level of experience
    yield<-ifelse(chosenActions[a]=="parent",
                  yield,
                  ifelse(foragingVariables$practice[foragingVariables==chosenActions[a]]==0,
                         yield,
                         yield*(1*log(agents[a,as.character(paste0(chosenActions[[a]],"Hist"))]+1)/log((1/epsilonDecay)/3))))
    

    #Determine the result of that transition
    result$yield[a]<-yield
    
  }
  
  #Output result tuples
  return(result)
}



#Social Learning#
#A function for learning a policy from observations rather than personal experiences
socialLearn<-function(theory,observations){
  
  #Randomly scramble the order of observations
  observations<-observations[sample(1:nrow(observations)),]
  
  #Loop through observations
  for(o in 1:nrow(observations)){
    
    #Pull out the focal observation
    observation<-observations[o,]
    
    #Identify the action-value function for the start state
    startStateQ<-theory[[observation$hhState]][observation$action, observation$startState]
    
    #Identify the expected action-value from choosing the most rewarding action in state S'
    newStateQ<-max(theory[[observation$hhState]][,observation$newState])
    
    #Implements action-value update based on the observation using theory-learning
    theory[[observation$hhState]][observation$action, observation$startState] <-
      startStateQ + learningRate * (observation$reward + (discount*newStateQ - startStateQ))
  }
  
  return(theory)
  
}



#Reward Calculation#
#A function for determining agents' reward given their states and actions
rewardUpdate<-function(agents,q,hhStates,actionResults,foragingVariables){
  
  #Create a dataframe reflecting the new household states
  newStates<-hhStates
  
  #Create a dataframe reflecting observations of the agents' outcomes (for social learning)
  observations<-actionResults
  
  #Add agent gamete size, household state, and reward columns to observations
  observations$gameteSize<-agents$gameteSizeGene1[match(observations$agentID,agents$ID)]
  observations$hhState<-agents$hhState[match(observations$agentID,agents$ID)]
  observations$reward<-0
  
  #Rearrange
  observations<-observations[,c(1:2,7:8,3:6,9)]
  
  #Loop through action results and update household states based on results
  for(a in 1:nrow(agents)){
    
    #Determine new household states
    newStates[newStates$hh==agents$hh[a],
          ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)]=="parent",2,
                 ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),
                        3,4))]<-newStates[newStates$hh==agents$hh[a],
          ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)]=="parent",2,
                 ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),3,4))] + 
      actionResults$yield[match(agents$ID[a],actionResults$agentID)]
    
    #Determine what resource the agent's action generated
    actionResource<-ifelse(actionResults$action[match(agents$ID[a],actionResults$agentID)]=="parent",1,
                           ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),2,3))
    
    #Calculate the reward this action should generate
    #Actions that generate any resource other than the one the household has the least of  results in decreased reward
    agentReward<-ifelse(actionResource==agents$hhState[agents$ID==actionResults$agentID[a]],
                        actionResults$yield[match(agents$ID[a],actionResults$agentID)],
                        actionResults$yield[match(agents$ID[a],actionResults$agentID)]*.25)
    
    #Update observations with reward
    observations$reward[match(agents$ID[a],observations$agentID)]<-agentReward
    

    #Update agents' total rewards
    agents$reward[a]<-agents$reward[a]+agentReward
    
    #Update agents' action history
    agents[a,as.character(paste0(actionResults$action[match(agents$ID[a],actionResults$agentID)],"Hist"))]<-agents[a,as.character(paste0(actionResults$action[match(agents$ID[a],actionResults$agentID)],"Hist"))]+1
    
    #Determine the action-value estimates for the current state-action pair and the best state-action pair in the new state
    currentStateQ<-q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]]
    newStateQ<-max(q[[as.character(agents$ID[a])]][[resample(which(newStates[newStates$hh == agents$hh[a], -1] == max(newStates[newStates$hh == agents$hh[a], -1])), 1)]][, actionResults$newState[match(agents$ID[a], actionResults$agentID)]])
    
    #Implements action-value update using Q-learning
    q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]] <-
      currentStateQ + learningRate * (agentReward + (discount*newStateQ - currentStateQ))
  }
  
  #Update household states
  hhStates<-newStates
  
  return(list(agents,q,hhStates,observations))
}



#Reproduce#
#Produce offspring from parents
reproduce <- function(agents, v) {
  
  #Calculate total reward achieved by household
  hhReward<-sapply(unique(agents$hh),function(x) sum(agents$reward[agents$hh==x]))
  
  #Rescale for use in determining relative reproductive success
  hhReward<-hhReward-min(hhReward)
  hhReward<-hhReward/max(hhReward)
  hhReward<-exp(selStrength*hhReward)
  
  #Determine which households get to produce offspring
  parents<-sample(1:length(hhReward),popSize,replace=T,prob=hhReward)
  
  #Create a blank dataframe for storing offspring
  offspring<-agents[0,1:(23+length(actions)+1)]
  
  #Initialize action value matrices for agents
  offspringQ <- lapply(1:popSize, function(x)
    lapply(1:3, function(y)
      matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        )))
  
  #Loop through reproducing agents
  for(r in 1:length(parents)){
    #Extract each parent
    parent1<-agents[agents$hh==unique(agents$hh)[parents[r]],][1,]
    parent2<-agents[agents$hh==unique(agents$hh)[parents[r]],][2,]
    
    #Determine which parents' genes will be expressed
    expressedParent<-sample(1:2,1)
    
    #Determine for both parents which of their genes will be inherited
    expressedGenes<-sample(1:2,2,replace=T)
    
    
    #Create the offspring using the randomly determined genes
    if(expressedParent==1){
      child<-cbind(parent1$ID,
                   if(expressedGenes[1]==1 | ((parent1$gameteSizeGene1 > 3) == 
                                           (parent1$gameteSizeGene2>3))){cbind(parent1$ID,parent1$policingGene1)} else {cbind(parent2$ID,parent2$policingGene1)},
                   if(expressedGenes[1]==1){parent1[,c(4:13)]} else{parent1[,c(14:23)]},
                   if(expressedGenes[2]==1){parent2[,c(4:13)]} else{parent2[,c(14:23)]},
                   parent1[,24:(23+length(actions)+1)])
    } else {
      child<-cbind(parent2$ID,
                   if(expressedGenes[1]==1 | ((parent2$gameteSizeGene1 > 3) == 
                                           (parent2$gameteSizeGene2>3))){cbind(parent2$ID,parent2$policingGene1)} else {cbind(parent1$ID,parent1$policingGene1)},
                   if(expressedGenes[1]==1){parent2[,c(4:13)]} else{parent2[,c(14:23)]},
                   if(expressedGenes[2]==1){parent1[,c(4:13)]} else{parent1[,c(14:23)]},
                   parent2[,24:(23+length(actions)+1)])
    }
    
    #Relabel columns
    colnames(child)<-colnames(offspring)
    
    #Add the child to the offspring dataframe
    offspring<-rbind(offspring,child)
  }
  
  offspring$ssParentPolice<-as.numeric(offspring$ssParentPolice)
  
  #Add mutation to relevant genes
  offspring$policingGene1<-rnorm(nrow(offspring),offspring$policingGene1,mutationRate)
  offspring$policingGene2<-rnorm(nrow(offspring),offspring$policingGene2,mutationRate)
  
  offspring$policingGene1<-ifelse(offspring$policingGene1>1,1,
                                       ifelse(offspring$policingGene1<0,0,
                                              offspring$policingGene1))
  
  offspring$policingGene2<-ifelse(offspring$policingGene2>1,1,
                                       ifelse(offspring$policingGene2<0,0,
                                              offspring$policingGene2))
  
  #Rename and re-label
  rownames(offspring)<-1:nrow(offspring)
  offspring$ID<-paste0(v,"-",1:nrow(offspring))
    
  names(offspringQ)<-offspring$ID
  
  #Set histories back to 0
  offspring[,24:(23+length(actions)+1)]<-0
  
  #Create a blank list for learned offspring theories as well
  offspringTheories<-list(offspringQ,offspringQ)
  
  #Output the offspring
  return(list(offspring,offspringQ, offspringTheories))
  
}

```



```{r modelStart}

#Number of Cores#
#Number of cores to use for the parallel loop
clust<-makeCluster(detectCores()-4)
registerDoParallel(clust)

#Loop through model loops
foreach(m = 0:(modelLoops-1)) %dopar% {
  
  #Loop through environment predictability
  for (e in environmentPredict) {
    
    #Loop through rates of environmental change
    for (c in envChange) {
      
      ###Environment Setup###
      
      #Set up environments
      environments <- lapply(1:numEnv, function(x)
        environmentSetup())
      
      
      ###Population Generation###
      
      #Generate the population
      popGen <- agentGenerate(m, actions, states)
      
      #Extract agents themselves
      agents <- popGen[[1]]
      
      #Extract initial action value functions
      q <- popGen[[2]]
      
      #Create a blank matrix of action-value functions for parents for now
      parentQs <- q
      
      #Extract initial (uninformed) agent social theories
      theories <- popGen[[3]]
      
      #Create a blank list for storing observations of agent behavior
      observations <- lapply(1:numEnv, function(x)
        NA)
      
      #Create a dataframe to store agents
      data <- lapply(1:numEnv, function(x)
        cbind(
          "modelLoop" = m + 1,
          "generation" = 0,
          "environmentChange" = c,
          agents[[x]]
        ))
      
      
      #Loop through generations
      for (g in 1:generations) {
        
        #Randomly change environments
        if (rbinom(1, 1, c)) {
          #Set up environments
          environments <- lapply(1:numEnv, function(x)
            environmentSetup())
          
        }
        
        for (v in 1:numEnv) {
          
          #Extract the current environment
          foragingVariables <- environments[[v]][[1]]
          tMatrices <- environments[[v]][[2]]
          
          #If at least one parent generation exists...
          if (g > 1) {
            #Offspring agents learn folk theories of policy from observing adults
            #They do so either with or without a theory that sex matters
            theories[[v]] <- lapply(1:2, function(x)
              #agents with no gender concept simply learn from all adults
              lapply(1:nrow(agents[[v]]), function(y)
                if (agents[[v]]$socialLearningGene1[y] < 2) {
                  socialLearn(theories[[v]][[x]][[y]], observations[[v]][sample(1:nrow(observations[[v]]), numObservations), ])
                } else {
                  #agents with a gender concept separately learn from large- and small-gamete producers
                  if (x == 1) {
                    socialLearn(theories[[v]][[x]][[y]], observations[[v]][sample(which((
                      observations[[v]]$gameteSize < 3
                    )), numObservations /
                      2) , ])
                  } else {
                    socialLearn(theories[[v]][[x]][[y]], observations[[v]][sample(which((
                      observations[[v]]$gameteSize > 3
                    )), numObservations /
                      2), ])
                  }
                  
                }))
            
            #Replace initial value function with folk theory for agents[[v]] that do social learning
            q[[v]] <- lapply(1:length(q[[v]]), function(x)
              if (agents[[v]]$socialLearningGene1[x] == 1) {
                theories[[v]][[1]][[x]]
              } else if (agents[[v]]$socialLearningGene1[x] == 2) {
                theories[[v]][[ifelse(agents[[v]]$gameteSizeGene1[x] < 3, 1, 2)]][[x]]
              } else {
                q[[v]][[x]]
              })
            
            #Relabel action-value functions
            names(q[[v]]) <- agents[[v]]$ID
          }
          
          #Mating:
          
          #Randomly pair each agent with an opposite-sex partner
          agents[[v]]$mID <- NA
          
          #Pair agents[[v]] with opposite sex partners
          if (sum(agents[[v]]$gameteSizeGene1 > 3) > sum(agents[[v]]$gameteSizeGene1 < 3)) {
            agents[[v]]$mID[agents[[v]]$gameteSizeGene1 < 3] <- sample(agents[[v]]$ID[agents[[v]]$gameteSizeGene1 > 3],
                                                                             nrow(agents[[v]][agents[[v]]$gameteSizeGene1 < 3, ]))
          } else {
            agents[[v]]$mID[agents[[v]]$gameteSizeGene1 > 3] <- sample(agents[[v]]$ID[agents[[v]]$gameteSizeGene1 < 3],
                                                                             nrow(agents[[v]][agents[[v]]$gameteSizeGene1 > 3, ]))
            
          }
          
          #Update mate IDs
          agents[[v]]$mID <- ifelse(is.na(agents[[v]]$mID) == 1,
                                       agents[[v]]$ID[match(agents[[v]]$ID, agents[[v]]$mID)],
                                       agents[[v]]$mID)
          
          #And rearrange by ID
          agents[[v]] <- agents[[v]][order(agents[[v]]$ID), ]
          
          #Remove agents who fail to pair
          agents[[v]] <- agents[[v]][!is.na(agents[[v]]$mID), ]
          
          #And remove their action value functions
          q[[v]] <- q[[v]][names(q[[v]]) %in% agents[[v]]$ID]
          
          
          
          #Household states:
          
          #Assign each agent a household ID which is just the lower of the two mated agents[[v]]' IDs
          agents[[v]]$hh <- pmin(agents[[v]]$ID, agents[[v]]$mID)
          
          #Create a variable to store current status of household resources
          #Starts with all but parenting set at 1 for simplicity
          hhStates <- data.frame(
            "hh" = unique(agents[[v]]$hh),
            "parenting" = 0,
            "nutrientM" = 1,
            "nutrientP" = 1
          )
          
          #Give all agents a random starting state
          agents[[v]]$state <- sample(states, nrow(agents[[v]]), replace = T)
          agents[[v]]$hhState <- sapply(agents[[v]]$hh, function(x)
            resample(which(hhStates[hhStates$hh == x, -1] == min(
              hhStates[hhStates$hh == x, -1]
            )), 1))
          
          #Loop through days of agents' lives
          for (l in 1:lifeSpan) {
            #Choose an action following epsilon-greedy policy
            chosenActions <- actionSelection(agents[[v]], q[[v]], parentQs[[v]])
            
            #Determine the state transitions and resource yield of those actions
            actionResults <- transitions(agents[[v]], chosenActions, tMatrices)
            
            #Update reward, action values, and household states
            reward <- rewardUpdate(agents[[v]],
                                   q[[v]],
                                   hhStates,
                                   actionResults,
                                   foragingVariables)
            
            #Update agents based on these reward updates
            agents[[v]] <- reward[[1]]
            
            #And action value functions based on whether agents learn or not
            q[[v]] <- reward[[2]]
            
            #And household states
            hhStates <- reward[[3]]
            
            #Update agent states
            agents[[v]]$state <- actionResults$newState[match(agents[[v]]$ID, actionResults$agentID)]
            
            #And update household states
            agents[[v]]$hhState <- sapply(agents[[v]]$hh, function(x)
              resample(which(hhStates[hhStates$hh == x, -1] == min(
                hhStates[hhStates$hh ==
                           x, -1]
              )), 1))
            
            #And if this is the last day of the life span...
            if (l == lifeSpan) {
              #Save the last set of decisions as observations for social learning
              observations[[v]] <- reward[[4]]
            }
          }
        }
        
        
        #Have agents reproduce in proportion to reward
        offspring <- lapply(1:numEnv, function(v)
          reproduce(agents[[v]], v))
        
        #Create a vector to determine which environment agents will be born into
        newEnv <- lapply(1:numEnv, function(v)
          ifelse(rbinom(nrow(offspring[[v]][[1]]), 1, 1 - e),
                 sample((1:numEnv)[-v],
                        nrow(offspring[[v]][[1]]), replace =T),
                 v))
       
        #Create a copy of offspring for shuffling
        shuffledOffspring<-offspring
        
        #Create a list of parent agent action values for shuffling
        shuffledQs<-q
       
        #Loop through environments
        for(v in 1:numEnv){
         
          #Maintain those offspring that will be born into this environment
          shuffledOffspring[[v]][[1]]<-offspring[[v]][[1]][newEnv[[v]]==v,]
          shuffledOffspring[[v]][[2]]<-offspring[[v]][[2]][newEnv[[v]]==v]
          shuffledOffspring[[v]][[3]][[1]]<-offspring[[v]][[3]][[1]][newEnv[[v]]==v]
          shuffledOffspring[[v]][[3]][[2]]<-offspring[[v]][[3]][[1]][newEnv[[v]]==v]
          
          #Shuffle parent action values
          shuffledQs[[v]]<-q[[v]][as.character(offspring[[v]][[1]][newEnv[[v]]==v,]$ssParentID)]
          
          #And add in offspring from other environments that will be born into this one
          for(n in (1:numEnv)[-v]){
            shuffledOffspring[[v]][[1]]<-rbind(shuffledOffspring[[v]][[1]],offspring[[n]][[1]][newEnv[[n]]==v,])
            shuffledOffspring[[v]][[2]]<-append(shuffledOffspring[[v]][[2]],offspring[[n]][[2]][newEnv[[n]]==v])
            shuffledOffspring[[v]][[3]][[1]]<-append(shuffledOffspring[[v]][[3]][[1]],offspring[[n]][[3]][[1]][newEnv[[n]]==v])
            shuffledOffspring[[v]][[3]][[2]]<-append(shuffledOffspring[[v]][[3]][[2]],offspring[[n]][[3]][[2]][newEnv[[n]]==v])
            
            shuffledQs[[v]]<-append(shuffledQs[[v]],q[[n]][as.character(offspring[[n]][[1]][newEnv[[n]]==v,]$ssParentID)])
          }
         
         
        }
       
        #Overwrite offspring with the shuffled populations
        offspring<-shuffledOffspring
        
        #Save parent agents to overall data frames (to preserve action history)
        data <- lapply(1:numEnv, function(x)
          rbind(
            data[[x]],
            cbind(
              "modelLoop" = m+1,
              "generation" = g,
              "environmentChange" = c,
              agents[[x]][,1:(23+length(actions)+1)]
            )
          ))
        
        #Overwrite parents with offspring
        parentQs<-shuffledQs
        agents <- lapply(1:numEnv, function(x)
          offspring[[x]][[1]])
        q <- lapply(1:numEnv, function(x)
          offspring[[x]][[2]])
        theories <- lapply(1:numEnv, function(x)
          offspring[[x]][[3]])
        
      }
      
      #Loop through environments
      for (v in 1:numEnv) {
        #Create a unique filename and filepath
        path <- "model-outputs/gender-policing/MSAG Policing Evolution Population "
        
        format <- ".csv"
        date <- format(Sys.time(), format = "%Y%m%d %H%M")
        file <- file.path(paste0(
          path,
          m + 1,
          "-",
          v,
          ifelse(e == max(envChange), " CHANGE HI ", " CHANGE LO "),
          date,
          format
        ))
        
        #Save model data
        write.csv(data[[v]], file = file, row.names = F)
      }
    }
  }
}

stopCluster(clust)

```
