```{r packages}
library(doParallel)
```



```{r parameters}

#Populations#
#The number of agent populations (determined by prior simulation)
populations<-which(grepl("PI HI",list.files("model-outputs/mating-strategy/",full.names=T)))



#Number of environments to simulate 
numEnv<-5



#Number of model loops
modelLoops<-length(populations)/numEnv



#Set desired population size
popSize<-300



#Generations#
#Number of generations
generations<-20



#Mutation Rate#
mutationRate<-.05



#Selection Strength#
#Strength of selection on productivity
selStrength<-10



#Environment Predictability#
#How predictable the agent's natal environment will be
environmentPredict<-c(0,1)



#Agent States#
#Create the set of possible states agents can be in
states<-c("parenting","successful","unsuccessful","injurySelf","injuryChild")



#Foraging Actions#
#Create the set of possible actions agents can take
actions<-c("parent",paste0("meat",1:5),paste0("plant",1:5))



#Lifespan#
#Number of learning trials agents experience
lifeSpan<-length(states)*length(actions)*10



#Learning Rate#
#Learning rate for Q-learning
learningRate<-.1



#Discount Rate#
#Discount rate for Q-learning
discount<-.9



#Epsilon#
#Initial epsilon for epislon greedy action selection
epsilon<-1



#Epsilon Decay Rate#
#How quickly epsilon decays with time
epsilonDecay<-1/lifeSpan



#Number of loops for planning agents to iterate
planningLoops<-20

```



```{r functions}


#Agent Generation#
#Generate the agents
agentGenerate <- function(m, actions, states) {
  
  #Identify populations that will be used for this run
  pops<-(1:length(populations) %% modelLoops)==m
  
  #Load the agents
  agents<-lapply(list.files("model-outputs/mating-strategy/",full.names=T)[which(grepl("PI HI",list.files("model-outputs/mating-strategy/",full.names=T)))][pops],read.csv)

  #Loop through populations
  for(l in 1:length(agents)){
    #Limit to just the final generation of agents[[l]]
    agents[[l]]<-agents[[l]][agents[[l]]$generation==max(agents[[l]]$generation),]
    
    #Remove modelLoop, generation, and selection columns for now
    agents[[l]]<-agents[[l]][,-(1:3)]
    
    #Relabel rows
    row.names(agents[[l]])<-1:nrow(agents[[l]])
    
    #Add a trait reflecting mating-parenting tradeoff, a mate preference, and corresponding trait
    agents[[l]]$learningGene1<-sample(0:2,nrow(agents[[l]]),replace=T)
    
    agents[[l]]$learningGene2<-sample(0:2,nrow(agents[[l]]),replace=T)
  
    #Rearrange
    agents[[l]]<-agents[[l]][,c(1:8,16,9:15,17)]
    
    #Create variables to track action history
    
    for(a in actions){
    agents[[l]]$x<-0
    
    colnames(agents[[l]])[ncol(agents[[l]])]<-paste0(a,"Hist")
    
    }
    
    #Store a reward value
    agents[[l]]$reward<-0
    
    #Create unique agent IDs
    agents[[l]]$ID<-paste0(l,"-",1:nrow(agents[[l]]))
  
  }
  
  
  #Initialize action value matrices for learning agents
  q <- lapply(1:length(agents),function(x)
              lapply(1:nrow(agents[[x]]), function(y)
    lapply(1:3, function(z)
      matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        )))
  )

  #Initialize action value matrices for non-learning agents
  qInherit <- lapply(1:length(agents), function(v)
    lapply(1:nrow(agents[[v]]), function(x)
      lapply(1:2, function(y)
        lapply(1:3, function(z)
          matrix(
            0, length(actions), length(states), dimnames = list(actions, states)
          )))))
    
  #Loop through inherited action value matrices
  for (env in 1:length(agents)) {
    for (l in 1:length(qInherit[[env]])) {
      #Set the initial inherited action-value for each forageable item based on the agents' natal environment
      qInherit[[env]][[l]][[1]][[1]][1, ] <- 1
      qInherit[[env]][[l]][[1]][[2]][sample(2:(1+length(actions[-1])/2),1), ] <- 1
      qInherit[[env]][[l]][[1]][[3]][sample((length(actions[-1])/2+2):length(actions),1), ] <- 1
      
      qInherit[[env]][[l]][[2]][[1]][1, ] <- 1
      qInherit[[env]][[l]][[2]][[2]][sample(2:(1+length(actions[-1])/2),1), ] <- 1
      qInherit[[env]][[l]][[2]][[3]][sample((length(actions[-1])/2+2):length(actions),1), ] <- 1
    }
  }
  
  
  #Create matrices for learned environment models
  models<-lapply(1:length(agents), function(x)
    lapply(1:nrow(agents[[x]]),function(y) NA))
  
  
  #Label action value matrices
  for(env in 1:length(agents)){
    names(q[[env]])<-agents[[env]]$ID
    names(qInherit[[env]])<-agents[[env]]$ID
    names(models[[env]])<-agents[[env]]$ID
  }
  
  
  #Output agents
  return(list(agents,q,qInherit,models))
}



#Improved Sampling#
#A sample function that will return a scalar if provided
resample<-function(x,n){
  if(length(x)>1){
    return(sample(x,n))
  } else{
    return(x)
  }
}



#Action Selection#
#A function for selecting actions given agents' action-value functions and learning rule
actionSelection<-function(agents,q, qInherit){
  
  #Loop through agents....
  chosenActions <- sapply(1:nrow(agents), function(x)
    
    if (agents$learningGene1[x] != 0) {
      #On Epsilon% of trials...
      if (rbinom(1, 1, max(c(.05, epsilon - epsilonDecay * l)))) {
        #Pick a random action
        sample(actions, 1)
      } else{
        #Otherwise, pick which ever action has maximum action value (ties broken randomly)
        actions[resample(which(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]] ==
                                 max(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]])), 1)]
      }
    } else {
      #If inherited, pick the action with the maximum action-value
      actions[resample(which(qInherit[[as.character(agents$ID[x])]][[1]][[agents$hhState[x]]][, agents$state[x]] ==
                                 max(qInherit[[as.character(agents$ID[x])]][[1]][[agents$hhState[x]]][, agents$state[x]])), 1)]
    }
  )
  
  #Output the actions
  return(chosenActions)
  
}



#Transition Matrix Setup
#A function to automatically generate transition matrices
#Creates a state transition matrix and a reward matrix
matrixSetup<-function(action, states, foragingVariables){
  
  #Action = action in question (parenting or a food)
  #States = possible agent stats
  #foraging Variables = variables about the foragable food items
  
  #If the action is parenting...
  if (action == "parent") {
    
    #Generate a blank matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    
    #Set transition to parenting to 1 for all starting states except states where agents are injured
    transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- 1
    
    #For the injury state, set transition to parenting to .8
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- .8
    
    #For the child injury state, set transition to parenting to .25
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- .25
    
    #Set transition back to injury states to .2 for agents who start injured
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")), (colnames(transMatrix[[1]]) %in% c("injurySelf"))] <-
      .2
    
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")), (colnames(transMatrix[[1]]) %in% c("injuryChild"))] <-
      .75
    
    #Return of successful parenting is always 1
    transMatrix[[2]][, colnames(transMatrix[[2]]) == "parenting"]<-1

  } else {
    
    #For any food items...
    
    #Create a blank transition matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    #If the food item is risky (i.e. not guaranteed success)
    if(foragingVariables$risk[foragingVariables$foodItem==action]==1){
      
      #Set the probability of success
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- .5
      
      #Set the probability of failure
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- .5
      
      #If the agent is injured, set the probability of transitioning back to that injured state at .2
      transMatrix[[1]]["injurySelf",
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      #And if the agent's child is inured set the probability of transitioning back to that injured state at .75
      transMatrix[[1]]["injuryChild",
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.75
      
      #And decrease the probability of success by 20% for injured agents
      transMatrix[[1]]["injurySelf",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injuryChild"))]<-
      (transMatrix[[1]]["injurySelf",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injuryChild"))])*.8
      
      #And by 75% for injured children
      transMatrix[[1]]["injuryChild",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injurySelf"))]<-
      (transMatrix[[1]]["injuryChild",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injurySelf"))])*.25
      

      
    } else {
      
      #If the food item is not risky (i.e. guaranteed success)...
      
      #Set the probability of success to 1
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- 1
      
      #And the probability of failure to 0
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- 0
      
      #If the agent is injured, set the probability of transitioning back to that injured state at .2
      transMatrix[[1]]["injurySelf",
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      #And if the agent's child is inured set the probability of transitioning back to that injured state at .5
      transMatrix[[1]]["injuryChild",
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.75
      
      #And decrease the probability of success by 20% for injured agents
      transMatrix[[1]]["injurySelf",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injuryChild"))]<-
      (transMatrix[[1]]["injurySelf",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injuryChild"))])*.8
      
      #And by 70% for injured children
      transMatrix[[1]]["injuryChild",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injurySelf"))]<-
      (transMatrix[[1]]["injuryChild",
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful","injurySelf"))])*.25

    }
    
    #If the food item is dangerous (poses an injury risk)...
    if(foragingVariables$danger[foragingVariables$foodItem==action] == 1){
      
      #Set the probability of transitioning to the injured state to 10%
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf")), colnames(transMatrix[[1]]) ==
                           "injurySelf"] <- .1
      
      #And decrease the probability of getting into the success states
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf")), colnames(transMatrix[[1]]) !=
                           "injurySelf"] <- transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf")), colnames(transMatrix[[1]]) !=
                           "injurySelf"]*.9
    }
    
    
    #If the foraging that food item is not compatible with child care...
    if (foragingVariables$childCompat[foragingVariables$foodItem==action] == 0) {
      
      #Set probability of injury to half the probability of succeeding, failing, or becoming injured
      transMatrix[[1]][1, "injuryChild"] <- sum(transMatrix[[1]][1, colnames(transMatrix[[1]]) != ("injuryChild")] *
                                                  .75)
      
      #And decrease the probability of the other states
      transMatrix[[1]][1, colnames(transMatrix[[1]]) != ("injuryChild")] <- transMatrix[[1]][1, colnames(transMatrix[[1]]) != ("injuryChild")] *
        .25
    }
    
    #Set the productivity of the food item
    #If the food item is productive, return 1/success rate (i.e., EV of foraging = 1),
    #Otherwise, set the expected value of foraging that food item to .5
    transMatrix[[2]][, "successful"] <- ifelse(foragingVariables$productivity[foragingVariables$foodItem ==
                                                                                action] == 1,
                                               1 / transMatrix[[1]]["successful", "successful"],
                                               .1 / transMatrix[[1]]["successful", "successful"])
    
  }

  #Output the transition matrix for this food item
  return(transMatrix)
  
}



#Environment Setup#
#A function to set up random environments
environmentSetup<-function(){
  
  #Create a dataframe reflecting the nature of foragable goods in this environment
  foragingVariables<-data.frame("foodItem"=actions[-1],
                                "productivity"=0,
                                "practice"=0,
                                "risk"=0,
                                "danger"=0,
                                "childCompat"=0)
  
  #Generate random environments
  #With the constraint that each environment has one of each food resource that is optimal
  foragingVariables$productivity<-c(sample(c(rep(0,length(actions[-1])/2-1),1)),
                                    sample(c(rep(0,length(actions[-1])/2-1),1)))


  
  foragingVariables$practice <- rbinom(nrow(foragingVariables),1,.5)
  foragingVariables$risk <- rbinom(nrow(foragingVariables),1,.5)
  foragingVariables$danger <- rbinom(nrow(foragingVariables),1,.5)
  foragingVariables$childCompat <- rbinom(nrow(foragingVariables),1,.5)
  
 
  #Generate transition matrices for this environment
  tMatrices <- lapply(actions, function(x)
    matrixSetup(x, states, foragingVariables))
  
  #Label appropriately
  names(tMatrices) <- actions
  
  return(list(foragingVariables,tMatrices))
  
}



#A function for executing transitions through the MDP given agents' actions
transitions<-function(agents,chosenActions,tMatrices){
  
  #Create a dataframe reflecting the result of each agent's action selection
  result<-data.frame("agentID"=agents$ID,
                     "hh"=agents$hh,
                     "startState"=agents$state,
                     "action"=chosenActions,
                     "newState"=rep(NA,nrow(agents)),
                     "yield"=NA)
  
    #Loop through agents
  for(a in 1:nrow(agents)){
    
    #Adjust agent state based on sex
    #Large gamete producers are treated as if they are in the parenting state with some probability
    #To represent minimum obligatory parental investment
    effectiveState<-ifelse(agents$gameteSizeGene1[a]<3,
                           agents$state[a],
                           ifelse(rbinom(1,1,.75),
                                  "parenting",
                                  agents$state[a]))
    
    #Determine the state transition
    result$newState[a]<-states[sample(1:length(states),
                               1,
                               prob=tMatrices[[chosenActions[a]]][[1]][effectiveState,])]
    
    #Determine yield of the agents' actions
    yield<-tMatrices[[chosenActions[a]]][[2]][effectiveState,result$newState[a]]
    
    #If the foraged good is practice-dependent, adjust yield based on level of experience
    yield<-ifelse(chosenActions[a]=="parent",
                  yield,
                  ifelse(foragingVariables$practice[foragingVariables==chosenActions[a]]==0,
                         yield,
                         yield*(1*log(agents[a,as.character(paste0(chosenActions[[a]],"Hist"))]+1)/log((1/epsilonDecay)/6))))
    

    #Determine the result of that transition
    result$yield[a]<-yield
    
  }
  
  #Output result tuples
  return(result)
}



#A function for updating q based on an environment model
planGenerate<-function(model){
  
  #Pick all prior trials that correspond to a randomly chosen starting household state
  simObs <- model[model$starthhState == resample(unique(model$starthhState), 1), ]
  
  #Pick all prior trials that correspond to a randomly chosen start state within that household state
  simObs <- simObs[simObs$startState == sample(unique(simObs$startState), 1), ]
  
  #Pick all prior trials that correspond to a randomly chosen prior action in that state
  simObs <- simObs[simObs$action == sample(unique(simObs$action), 1), ]
  
  #Finally, if more than one prior trial remains...
  if (nrow(simObs) > 1) {
    #...pick one at random
    simObs <- simObs[sample(1:nrow(simObs), 1), ]
  }
  
  return(simObs)
  
}



#Reward Calculation#
#A function for determining agents' reward given their states and actions
rewardUpdate <- function(agents,
                         q,
                         models,
                         hhStates,
                         actionResults,
                         foragingVariables) {
  #Create a dataframe reflecting the new household states
  newStates <- hhStates
  
  #Create a dataframe reflecting observations of the agents' outcomes (for social learning)
  observations <- actionResults
  
  #Add agent gamete size, household state, and reward columns to observations
  observations$gameteSize <- agents$gameteSizeGene1[match(observations$agentID, agents$ID)]
  observations$starthhState <- agents$hhState[match(observations$agentID, agents$ID)]
  observations$newhhState <- 0
  observations$reward <- 0
  
  #Rearrange
  observations <- observations[, c(1:2, 7:9, 3:6, 10)]
  
  #Loop through action results and update household states based on results
  for (a in 1:nrow(agents)) {
    #Determine new household states
    newStates[newStates$hh == agents$hh[a], ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)] ==
                                                     "parent", 2, ifelse(grepl("meat.", actionResults$action[match(agents$ID[a], actionResults$agentID)]), 3, 4))] <-
      newStates[newStates$hh == agents$hh[a], ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)] ==
                                                       "parent", 2, ifelse(grepl("meat.", actionResults$action[match(agents$ID[a], actionResults$agentID)]), 3, 4))] +
      actionResults$yield[match(agents$ID[a], actionResults$agentID)]
    
    #Determine the new household state in light of the agent's action
    newhhstate <- resample(which(newStates[newStates$hh == agents$hh[a], -1] == min(newStates[newStates$hh == agents$hh[a], -1])), 1)
    
    #Store this new household state
    observations$newhhState[match(agents$ID[a], observations$agentID)] <-
      newhhstate
    
    #Determine what resource the agent's action generated
    actionResource <- ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)] ==
                               "parent", 1, ifelse(grepl("meat.", actionResults$action[match(agents$ID[a], actionResults$agentID)]), 2, 3))
    
    #Calculate the reward this action should generate
    #Actions that generate any resource other than the one the household has the least of  results in decreased reward
    agentReward <- ifelse(
      actionResource == agents$hhState[agents$ID == actionResults$agentID[a]],
      actionResults$yield[match(agents$ID[a], actionResults$agentID)],
      actionResults$yield[match(agents$ID[a], actionResults$agentID)] *
        .5
    )
    
    #Update observations with reward
    observations$reward[match(agents$ID[a], observations$agentID)] <- agentReward
    
    
    #Update agents' total rewards
    agents$reward[a] <- agents$reward[a] + agentReward
    
    #Update agents' action history
    agents[a, as.character(paste0(actionResults$action[match(agents$ID[a], actionResults$agentID)], "Hist"))] <-
      agents[a, as.character(paste0(actionResults$action[match(agents$ID[a], actionResults$agentID)], "Hist"))] +
      1
    
    #Determine the action-value estimates for the current state-action pair and the best state-action pair in the new state
    currentStateQ <- q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]]
    newStateQ <- max(q[[as.character(agents$ID[a])]][[newhhstate]][, actionResults$newState[match(agents$ID[a], actionResults$agentID)]])
    
    #Implements action-value update using Q-learning
    q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]] <-
      currentStateQ + learningRate * (agentReward + (discount * newStateQ - currentStateQ))
    
    #If the agents engage in model-based RL...
    if (agents$learningGene1[a] == 2) {
      #If the agent has no model...
      if (is.na(models[[as.character(agents$ID[a])]])[1]) {
        #Create a blank dataframe to store the agent's model
        models[[as.character(agents$ID[a])]] <- observations[0, ]
      }
      
      #If the model has become too large...
      if (nrow(models[[as.character(agents$ID[a])]]) >= 100) {
        #Remove the oldest memory
        #This prevents the model information from becoming stale for practice-dependent actions
        models[[as.character(agents$ID[a])]] <- models[[as.character(agents$ID[a])]][-1, ]
        
      }
      
      #Update agent's model with their behavior from this round
      models[[as.character(agents$ID[a])]] <- rbind(models[[as.character(agents$ID[a])]], observations[match(agents$ID[a], observations$agentID), ])
      
      
      #Generate observations to plan from
      simObs <- t(sapply(1:planningLoops, function(x)
        planGenerate(models[[as.character(agents$ID[a])]])))
      
      #Loop through plan steps
      for (p in 1:nrow(simObs)) {
        #Identify the action-value function for the start state
        startStateQ <- q[[as.character(agents$ID[a])]][[simObs[p, ]$starthhState]][simObs[p, ]$action, simObs[p, ]$startState]
        
        #Identify the expected action-value from choosing the most rewarding action in state S'
        newStateQ <- max(q[[as.character(agents$ID[a])]][[simObs[p, ]$newhhState]][, simObs[p, ]$newState])
        
        #Implements action-value update based on the simObs[p,] using q-learning
        q[[as.character(agents$ID[a])]][[simObs[p, ]$starthhState]][simObs[p, ]$action, simObs[p, ]$startState] <-
          startStateQ + learningRate * (simObs[p, ]$reward + (discount * newStateQ - startStateQ))
      }
    }
  }
  
  #Update household states
  hhStates <- newStates
  
  return(list(agents, q, models, hhStates, observations))
}







#Reproduce#
#Produce offspring from parents
reproduce <- function(agents, qInherit, v) {
  
  #Calculate total reward achieved by household
  hhReward<-sapply(unique(agents$hh),function(x) sum(agents$reward[agents$hh==x]))
  
  #Rescale for use in determining relative reproductive success
  hhReward<-hhReward-min(hhReward)
  hhReward<-hhReward/max(hhReward)
  hhReward<-hhReward+1/selStrength
  
  #Determine which households get to produce offspring
  parents<-sample(1:length(hhReward),popSize,replace=T,prob=hhReward)
  
  #Create a blank dataframe for storing offspring
  offspring<-agents[0,1:(17+length(actions)+1)]
  
  #Initialize action value matrices for agents
  offspringQ <- lapply(1:popSize, function(x)
    lapply(1:3, function(x)
      matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        )))

  #Initialize action probability weights for non-learning agents
  offspringQInherit<-lapply(1:popSize,function(x)
    lapply(1:2,function(z)
      lapply(1:3, function(y)
        matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        ))
      )
    )
  
  #Loop through reproducing agents
  for(r in 1:length(parents)){
    #Extract each parent
    parent1<-agents[agents$hh==unique(agents$hh)[parents[r]],][1,]
    parent2<-agents[agents$hh==unique(agents$hh)[parents[r]],][2,]
    
    #Determine which parents' genes will be expressed
    expressedParent<-sample(1:2,1)
    
    #Determine for both parents which of their genes will be inherited
    expressedGenes<-sample(1:2,2,replace=T)
    
    #Create the offspring using the randomly determined genes
    if(expressedParent==1){
      child<-cbind(parent1$ID,
                   if(expressedGenes[1]==1){parent1[,c(2:9)]} else{parent1[,c(10:17)]},
                   if(expressedGenes[2]==1){parent2[,c(2:9)]} else{parent2[,c(10:17)]},
                   parent1[,18:(17+length(actions)+1)])
      
      offspringQInherit[[r]][[1]]<-qInherit[[as.character(parent1$ID)]][[expressedGenes[1]]]
      offspringQInherit[[r]][[2]]<-qInherit[[as.character(parent2$ID)]][[expressedGenes[2]]]
    } else {
      child<-cbind(parent2$ID,
                   if(expressedGenes[1]==1){parent2[,c(2:9)]} else{parent2[,c(10:17)]},
                   if(expressedGenes[2]==1){parent1[,c(2:9)]} else{parent1[,c(10:17)]},
                   parent2[,18:(17+length(actions)+1)])
      offspringQInherit[[r]][[1]]<-qInherit[[as.character(parent2$ID)]][[expressedGenes[1]]]
      offspringQInherit[[r]][[2]]<-qInherit[[as.character(parent1$ID)]][[expressedGenes[2]]]
    }
    
    #Relabel columns
    colnames(child)<-colnames(offspring)
    
    #Add the child to the offspring dataframe
    offspring<-rbind(offspring,child)
  }
  
  #Add mutation to relevant genes
  offspring$learningGene1<-ifelse(rbinom(nrow(offspring),1,mutationRate),
                                  sample(0:2,nrow(offspring),replace=T),
                                  offspring$learningGene1)
  
  offspring$learningGene2<-ifelse(rbinom(nrow(offspring),1,mutationRate),
                                  sample(0:2,nrow(offspring),replace=T),
                                  offspring$learningGene2)
  
  
  offspringQInherit<-lapply(1:length(offspringQInherit),function(x)
    lapply(1:2,function(y) 
      lapply(1:3,function(z)
          offspringQInherit[[x]][[y]][[z]]+rnorm(length(actions)*length(states),0,mutationRate)
          )
    )
  )
  
  #Prevent values below 0 or above 1
  offspringQInherit<-lapply(1:length(offspringQInherit),function(x)
    lapply(1:2,function(y)
      lapply(1:3,function(z) 
      ifelse(offspringQInherit[[x]][[y]][[z]]<0,
                    0,
                    ifelse(offspringQInherit[[x]][[y]][[z]]>1,
                           1,offspringQInherit[[x]][[y]][[z]]))
    )
      )
    
  )
  
  #Rename and re-label
  rownames(offspring)<-1:nrow(offspring)
  offspring$ID<-paste0(v,"-",1:nrow(offspring))
    
  names(offspringQ)<-paste0(v,"-",1:nrow(offspring))
  names(offspringQInherit)<-paste0(v,"-",1:nrow(offspring))
  
  #Set histories back to 0
  offspring[,18:(17+length(actions)+1)]<-0
  
  #Create a blank list for learned offspring theories as well
  offspringModels<-lapply(1:nrow(offspring),function(x) NA)
  
  names(offspringModels)<-offspring$ID
  
  #Output the offspring
  return(list(offspring,offspringQ,offspringQInherit,offspringModels))
  
}


```



```{r modelStart}

#Number of Cores#
#Number of cores to use for the parallel loop
clust<-makeCluster(detectCores()-4)
registerDoParallel(clust)

#Loop through model loops
foreach(m = 0:(modelLoops-1)) %dopar% {
  
  #Loop through environment predictability
  for (e in environmentPredict) {
    
    ###Environment Setup###
    
    #Set up environments
    environments <- lapply(1:numEnv, function(x)
      environmentSetup())
    
    
    
    ###Population Generation###
    
    #Generate the population
    popGen <- agentGenerate(m, actions, states)
    
    #Extract agents themselves
    agents <- popGen[[1]]
    
    #Extract initial action value functions
    q <- popGen[[2]]
    
    #Extract inherited q values
    qInherit <- popGen[[3]]
    
    models <- popGen[[4]]
    
    
    #Create a dataframe to store agents
    data <- lapply(1:numEnv, function(x)
      cbind(
        "modelLoop" = m + 1,
        "generation" = 0,
        "environmentPredict" = e,
        agents[[x]]
      ))
    
    #Loop through generations
    for (g in 1:generations) {
      #Loop through environments
      for (v in 1:numEnv) {
        #Extract the current environment
        foragingVariables <- environments[[v]][[1]]
        tMatrices <- environments[[v]][[2]]
        
        #Mating:
        
        #Randomly pair each agent with an opposite-sex partner
        agents[[v]]$mID <- NA
        
        #Split agents into learners and non-learners
        modelers <- agents[[v]][agents[[v]]$learningGene1 == 2, ]
        learners <- agents[[v]][agents[[v]]$learningGene1 == 1, ]
        nonLearners <- agents[[v]][agents[[v]]$learningGene1 == 0, ]
        
        #Pair agents with opposite sex partners
        if (sum(modelers$gameteSizeGene1 > 3) > sum(modelers$gameteSizeGene1 <
                                                    3)) {
          modelers$mID[modelers$gameteSizeGene1 < 3] <- sample(modelers$ID[modelers$gameteSizeGene1 > 3], nrow(modelers[modelers$gameteSizeGene1 < 3, ]))
        } else {
          modelers$mID[modelers$gameteSizeGene1 > 3] <- sample(modelers$ID[modelers$gameteSizeGene1 < 3], nrow(modelers[modelers$gameteSizeGene1 > 3, ]))
          
        }
        
        #Update mate IDs
        modelers$mID <- ifelse(is.na(modelers$mID) == 1, modelers$ID[match(modelers$ID, modelers$mID)], modelers$mID)
        
        #Pair agents with opposite sex partners
        if (sum(learners$gameteSizeGene1 > 3) > sum(learners$gameteSizeGene1 <
                                                    3)) {
          learners$mID[learners$gameteSizeGene1 < 3] <- sample(learners$ID[learners$gameteSizeGene1 > 3], nrow(learners[learners$gameteSizeGene1 < 3, ]))
        } else {
          learners$mID[learners$gameteSizeGene1 > 3] <- sample(learners$ID[learners$gameteSizeGene1 < 3], nrow(learners[learners$gameteSizeGene1 > 3, ]))
          
        }
        
        #Update mate IDs
        learners$mID <- ifelse(is.na(learners$mID) == 1, learners$ID[match(learners$ID, learners$mID)], learners$mID)
        
        #Pair agents with opposite sex partners
        if (sum(nonLearners$gameteSizeGene1 > 3) > sum(nonLearners$gameteSizeGene1 <
                                                       3)) {
          nonLearners$mID[nonLearners$gameteSizeGene1 < 3] <- sample(nonLearners$ID[nonLearners$gameteSizeGene1 > 3], nrow(nonLearners[nonLearners$gameteSizeGene1 < 3, ]))
        } else {
          nonLearners$mID[nonLearners$gameteSizeGene1 > 3] <- sample(nonLearners$ID[nonLearners$gameteSizeGene1 < 3], nrow(nonLearners[nonLearners$gameteSizeGene1 > 3, ]))
          
        }
        
        #Update mate IDs
        nonLearners$mID <- ifelse(is.na(nonLearners$mID) == 1,
                                  nonLearners$ID[match(nonLearners$ID, nonLearners$mID)],
                                  nonLearners$mID)
        
        #Re-merge agents
        agents[[v]] <- rbind(modelers, learners, nonLearners)
        
        agents[[v]] <- agents[[v]][order(agents[[v]]$ID), ]
        
        #Remove agents who fail to pair
        agents[[v]] <- agents[[v]][!is.na(agents[[v]]$mID), ]
        
        #And remove their action value functions
        q[[v]] <- q[[v]][names(q[[v]]) %in% agents[[v]]$ID]
        qInherit[[v]] <- qInherit[[v]][names(qInherit[[v]]) %in% agents[[v]]$ID]
        models[[v]] <- models[[v]][names(models[[v]]) %in% agents[[v]]$ID]
        
        
        
        #Household states:
        
        #Assign each agent a household ID which is just the lower of the two mated agents' IDs
        agents[[v]]$hh <- pmin(agents[[v]]$ID, agents[[v]]$mID)
        
        #Create a variable to store current status of household resources
        #Starts with all but parenting set at 1 for simplicity
        hhStates <- data.frame(
          "hh" = unique(agents[[v]]$hh),
          "parenting" = 0,
          "nutrientM" = 1,
          "nutrientP" = 1
        )
        
        #Give all agents a random starting state
        agents[[v]]$state <- sample(states, nrow(agents[[v]]), replace = T)
        agents[[v]]$hhState <- sapply(agents[[v]]$hh, function(x)
          resample(which(hhStates[hhStates$hh == x, -1] == min(hhStates[hhStates$hh == x, -1])), 1))
        
        #Loop through days of agents' lives
        for (l in 1:lifeSpan) {
          #Choose an action following epsilon-greedy policy
          chosenActions <- actionSelection(agents[[v]], q[[v]], qInherit[[v]])
          
          #Determine the state transitions and resource yield of those actions
          actionResults <- transitions(agents[[v]], chosenActions, tMatrices)
          
          #Update reward, action values, and household states
          reward <- rewardUpdate(agents[[v]],
                                 q[[v]],
                                 models[[v]],
                                 hhStates,
                                 actionResults,
                                 foragingVariables)
          
          #Update agents based on these reward updates
          agents[[v]] <- reward[[1]]
          
          #And action value functions based on whether agents learn or not
          q[[v]] <- reward[[2]]
          
          #And agent models
          models[[v]] <- reward[[3]]
          
          #And household states
          hhStates <- reward[[4]]
          
          #Update agent states
          agents[[v]]$state <- actionResults$newState[match(agents[[v]]$ID, actionResults$agentID)]
          
          #And update household states
          agents[[v]]$hhState <- sapply(agents[[v]]$hh, function(x)
            resample(which(hhStates[hhStates$hh == x, -1] == min(hhStates[hhStates$hh ==
                                                                            x, -1])), 1))
          
        }
        
      }
      
      #Have agents reproduce in proportion to reward
      offspring <- lapply(1:numEnv, function(v)
        reproduce(agents[[v]], qInherit[[v]], v))
      
      #Create a vector to determine which environment agents will be born into
      newEnv <- lapply(1:numEnv, function(v)
        ifelse(rbinom(nrow(offspring[[v]][[1]]), 1, 1 - e), sample((1:numEnv)[-v], nrow(offspring[[v]][[1]]), replace =
                                                                     T
        ), v))
      
      #Create a copy of offspring for shuffling
      shuffledOffspring <- offspring
      
      #Loop through environments
      for (v in 1:numEnv) {
        #Maintain those offspring that will be born into this environment
        shuffledOffspring[[v]][[1]] <- offspring[[v]][[1]][newEnv[[v]] ==
                                                             v, ]
        shuffledOffspring[[v]][[2]] <- offspring[[v]][[2]][newEnv[[v]] ==
                                                             v]
        shuffledOffspring[[v]][[3]] <- offspring[[v]][[3]][newEnv[[v]] ==
                                                             v]
        shuffledOffspring[[v]][[4]] <- offspring[[v]][[4]][newEnv[[v]] ==
                                                             v]
        
        #And add in offspring from other environments that will be born into this one
        for (n in (1:numEnv)[-v]) {
          shuffledOffspring[[v]][[1]] <- rbind(shuffledOffspring[[v]][[1]], offspring[[n]][[1]][newEnv[[n]] ==
                                                                                                  v, ])
          shuffledOffspring[[v]][[2]] <- append(shuffledOffspring[[v]][[2]], offspring[[n]][[2]][newEnv[[n]] ==
                                                                                                   v])
          shuffledOffspring[[v]][[3]] <- append(shuffledOffspring[[v]][[3]], offspring[[n]][[3]][newEnv[[n]] ==
                                                                                                   v])
          shuffledOffspring[[v]][[4]] <- append(shuffledOffspring[[v]][[4]], offspring[[n]][[4]][newEnv[[n]] ==
                                                                                                   v])
          
        }
        
        
      }
      
      #Overwrite offspring with the shuffled populations
      offspring <- shuffledOffspring
      
      #Save parent agents to overall data frames (to preserve action history)
      data <- lapply(1:numEnv, function(x)
        rbind(
          data[[x]],
          cbind(
            "modelLoop" = m,
            "generation" = g,
            "environmentPredict" = e,
            agents[[x]][, 1:(17 + length(actions) + 1)]
          )
        ))
      
      #Overwrite parents with offspring
      agents <- lapply(1:numEnv, function(x)
        offspring[[x]][[1]])
      q <- lapply(1:numEnv, function(x)
        offspring[[x]][[2]])
      qInherit <- lapply(1:numEnv, function(x)
        offspring[[x]][[3]])
      models <- lapply(1:numEnv, function(x)
        offspring[[x]][[4]])
      
    }
    
    #Loop through environments
    for (v in 1:numEnv) {
      #Create a unique filename and filepath
      path <- "model-outputs/foraging/learning-evolution/MSAG Foraging LE Population "
      
      format <- ".csv"
      date <- format(Sys.time(), format = "%Y%m%d %H%M")
      file <- file.path(paste0(
        path,
        m + 1,
        "-",
        v,
        ifelse(e == max(environmentPredict), " PREDICT HI ", " PREDICT LO "),
        date,
        format
      ))
      
      #Save model data
      write.csv(data[[v]], file = file, row.names = F)
    }
    
    
  }
  
}
  

stopCluster(clust)

```
