```{r packages}

```



```{r parameters}

#Populations#
#The number of agent populations (determined by prior simulation)
populations<-which(grepl("PI HI",list.files("model-outputs/mating-strategy/",full.names=T)))[1]



#Generations#
#Number of generations
generations<-1



#Environments#
#Determine which of two environments to simulate
environments<-1:3



#Agent States#
#Create the set of possible states agents can be in
states<-c("parenting","successful","unsuccessful","injurySelf","injuryChild")



#Foraging Actions#
#Create the set of possible actions agents can take
actions<-c("parent",paste0("meat",1:5),paste0("plant",1:5))



#Lifespan#
#Number of learning trials agents experience
lifeSpan<-length(states)*length(actions)*100



#Learning Rate#
#Learning rate for Q-learning
learningRate<-.1



#Discount Rate#
#Discount rate for Q-learning
discount<-.9



#Epsilon#
#Initial epsilon for epislon greedy action selection
epsilon<-1



#Epsilon Decay Rate#
#How quickly epsilon decays with time
epsilonDecay<-1/(length(states)*length(actions)*10)

```



```{r functions}

#Agent Generation#
#Generate the agents
agentGenerate <- function(population, actions, states) {
  
  #Load the agents
  agents<-read.csv(list.files("model-outputs/mating-strategy/",full.names=T)[population])
  
  #Limit to just the final generation of agents
  agents<-agents[agents$generation==max(agents$generation),]
  
  #Remove modelLoop, generation, and selection columns for now
  agents<-agents[,-(1:3)]
  
  #Relabel rows
  row.names(agents)<-1:nrow(agents)
  
  #Add a trait reflecting mating-parenting tradeoff, a mate preference, and corresponding trait
  agents$learningGene1<-rbinom(nrow(agents),1,1)
  
  agents$learningGene2<-rbinom(nrow(agents),1,1)

  #Rearrange
  agents<-agents[,c(1:8,16,9:15,17)]
  
  for(a in actions){
  agents$x<-0
  
  colnames(agents)[ncol(agents)]<-paste0(a,"Hist")
  
  }
  
  #Store a reward value
  agents$reward<-0
  
  #Initialize action value matrices for learning agents
  q <- lapply(1:nrow(agents), function(x)
    lapply(1:3, function(x)
      matrix(
          0,
          length(actions),
          length(states),
          dimnames = list(actions, states)
        )))
  
  
  #Label action value matrioces    
  names(q)<-agents$ID
  
  #Output agents
  return(list(agents,q))
}



#Improved Sampling#
#A sample function that will return a scalar if provided
resample<-function(x,n){
  if(length(x)>1){
    return(sample(x,n))
  } else{
    return(x)
  }
}



#Action Selection#
#A function for selecting actions given agents' action-value functions and learning rule
actionSelection<-function(agents,q){
  
  #Loop through agents....
  chosenActions <- sapply(1:nrow(agents), function(x)
    
      #On Epsilon% of trials...
      if (rbinom(1, 1, rbinom(1, 1, max(c(.05, epsilon - epsilonDecay * l))))) {
        #Pick a random action
        sample(actions, 1)
      } else{
        #Otherwise, pick which ever action has maximum action value (ties broken randomly)
        actions[resample(which(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]] ==
                                 max(q[[as.character(agents$ID[x])]][[agents$hhState[x]]][, agents$state[x]])), 1)]
      }

  )
  
  #Output the actions
  return(chosenActions)
  
}



#Transition Matrix Setup
#A function to automatically generate transition matrices
#Creates a state transition matrix and a reward matrix
matrixSetup<-function(action, states, foragingVariables){
  
  #Action = action in question (parenting or a food)
  #States = possible agent stats
  #foraging Variables = variables about the foragable food items
  
  #If the action is parenting...
  if (action == "parent") {
    
    #Generate a blank matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    
    #Set transition to parenting to 1 for all starting states except states where agents are injured
    transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- 1
    
    #For states with injury, set transition to parenting to .8
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "parenting"] <- .8
    
    #Set transition back to injury states to .2 for agents who start injured
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")), (colnames(transMatrix[[1]]) %in% c("injurySelf"))] <-
      .2
    
    transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")), (colnames(transMatrix[[1]]) %in% c("injuryChild"))] <-
      .2
    
    #Return of successful parenting is always 1
    transMatrix[[2]][, colnames(transMatrix[[2]]) == "parenting"]<-1

  } else {
    
    #For any food items...
    
    #Create a blank transition matrix
    transMatrix <- lapply(1:2,function(x) 
      matrix(0, length(states), length(states),dimnames = list(states,states)))
    
    #If the food item is risky (i.e. not guaranteed success)
    if(foragingVariables$risk[foragingVariables$foodItem==action]==1){
      
      #Set the probability of success
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- .5
      
      #Set the probability of failure
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- .5
      
      #If the agent is injured, decrease the probability of success by 80%
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))]<-
      (transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))])*.8
      
      #And set the probability of transitioning back to that injured state at .8
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")),
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")),
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.2
      
    } else {
      
      #If the food item is not risky (i.e. guaranteed success)...
      
      #Set the probability of success to 1
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "successful"] <- 1
      
      #And the probability of failure to 0
      transMatrix[[1]][,colnames(transMatrix[[1]]) == "unsuccessful"] <- 0
      
      #Except if the agent is injured, then the probability of success is 80% and the probability of remaining in the injured state is 20%
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))]<-
      (transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")),
                     (colnames(transMatrix[[1]]) %in% c("successful", "unsuccessful"))])*.8
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injurySelf")),
                       (colnames(transMatrix[[1]]) %in% c("injurySelf"))]<-.2
      
      transMatrix[[1]][(rownames(transMatrix[[1]]) %in% c("injuryChild")),
                       (colnames(transMatrix[[1]]) %in% c("injuryChild"))]<-.2

    }
    
    #If the food item is dangerous (poses an injury risk)...
    if(foragingVariables$danger[foragingVariables$foodItem==action] == 1){
      
      #Set the probability of transitioning to the injured state to 10%
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) ==
                           "injurySelf"] <- .1
      
      #And decrease the probability of getting into the success states
      transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) !=
                           "injurySelf"] <- transMatrix[[1]][!(rownames(transMatrix[[1]]) %in% c("injurySelf", "injuryChild")), colnames(transMatrix[[1]]) !=
                           "injurySelf"]*.9
    }
    
    
    #If the foraging that food item is not compatible with child care...
    if (foragingVariables$childCompat[foragingVariables$foodItem==action] == 0) {
      
      #Set probability of injury to half the probability of succeeding or failing
      transMatrix[[1]][1, "injuryChild"] <- sum(transMatrix[[1]][1, c("successful", "unsuccessful")] *
                                                  .75)
      
      #And decrease the probability of succeeding or failing
      transMatrix[[1]][1, c("successful", "unsuccessful")] <- transMatrix[[1]][1, c("successful", "unsuccessful")] *
        .25
    }
    
    #Set the productivity of the food item
    #If the food item is productive, return 1/success rate (i.e., EV of foraging = 1),
    #Otherwise, set the expected value of foraging that food item to .5
    transMatrix[[2]][, "successful"] <- ifelse(foragingVariables$productivity[foragingVariables$foodItem ==
                                                                                action] == 1,
                                               1 / transMatrix[[1]]["successful", "successful"],
                                               .1 / transMatrix[[1]]["successful", "successful"])
    
  }

  #Output the transition matrix for this food item
  return(transMatrix)
  
}



#Environment Setup#
#A function to set up random environments
environmentSetup<-function(environment){
  
  #Create a dataframe reflecting the nature of foragable goods in this environment
  foragingVariables<-data.frame("foodItem"=actions[-1],
                                "productivity"=0,
                                "practice"=0,
                                "risk"=0,
                                "danger"=0,
                                "childCompat"=0)
  
  #Generate an environment in which optimal foraging policy is either not sex-differentiated (e=1), is sex-differentiated (e=2), or is sex-differentiated but multiple within-sex optima (e=3)
  if (environment==1) {
    foragingVariables$productivity <- rep(c(1,rep(0,length(actions[-1])/2-1)),2)
    foragingVariables$practice <- c(1,rep(0,length(actions[-(1:2)])))
    foragingVariables$risk <- rep(c(1,0),each=length(actions[-1])/2)
    foragingVariables$danger <- c(1,rep(0,length(actions[-(1:2)])))
    foragingVariables$childCompat <- rep(c(0,1),each=length(actions[-1])/2)
  } else if (environment==2) {
    foragingVariables$productivity <- rep(c(1,rep(0,length(actions[-1])/2-1)),2)
    foragingVariables$practice <- c(0,rep(0,length(actions[-(1:2)])))
    foragingVariables$risk <- rep(c(0,rep(1,length(actions[-1])/2-1)),2)
    foragingVariables$danger <- rep(c(0,rep(1,length(actions[-1])/2-1)),2)
    foragingVariables$childCompat <- rep(1,length(actions[-1]))
  } else {
    foragingVariables$productivity <- c(1,rep(0,length(actions[-1])/2-1),rep(1,2),rep(0,length(actions[-1])/2-2))
    foragingVariables$practice <- c(1,rep(0,length(actions[-1])/2-1),rep(1,2),rep(0,length(actions[-1])/2-2))
    foragingVariables$risk <- rep(c(1,0),each=length(actions[-1])/2)
    foragingVariables$danger <- c(1,rep(0,length(actions[-(1:2)])))
    foragingVariables$childCompat <- rep(c(0,1),each=length(actions[-1])/2)
  }
 
  #Generate transition matrices for this environment
  tMatrices <- lapply(actions, function(x)
    matrixSetup(x, states, foragingVariables))
  
  #Label appropriately
  names(tMatrices) <- actions
  
  return(list(foragingVariables,tMatrices))
  
}



#A function for executing transitions through the MDP given agents' actions
transitions<-function(agents,chosenActions,tMatrices){
  
  #Create a dataframe reflecting the result of each agent's action selection
  result<-data.frame("agentID"=agents$ID,
                     "hh"=agents$hh,
                     "startState"=agents$state,
                     "action"=chosenActions,
                     "newState"=rep(NA,nrow(agents)),
                     "yield"=NA)
  
    #Loop through agents
  for(a in 1:nrow(agents)){
    
    #Adjust agent state based on sex
    #Large gamete producers are treated as if they are in the parenting state with some probability
    #To represent minimum obligatory parental investment
    effectiveState<-ifelse(agents$gameteSizeGene1[a]<3,
                           agents$state[a],
                           ifelse(rbinom(1,1,.5),
                                  "parenting",
                                  agents$state[a]))
    
    #Determine the state transition
    result$newState[a]<-states[sample(1:length(states),
                               1,
                               prob=tMatrices[[chosenActions[a]]][[1]][effectiveState,])]
    
    
    #Determine yield of the agents' actions
    yield<-tMatrices[[chosenActions[a]]][[2]][effectiveState,result$newState[a]]
    
    #If the foraged good is practice-dependent, adjust yield based on level of experience
    yield<-ifelse(chosenActions[a]=="parent",
                  yield,
                  ifelse(foragingVariables$practice[foragingVariables==chosenActions[a]]==0,
                         yield,
                         yield*(1*log(agents[a,as.character(paste0(chosenActions[[a]],"Hist"))]+1)/log((lifeSpan)/3))))
    

    #Determine the result of that transition
    result$yield[a]<-yield
    
  }
  
  #Output result tuples
  return(result)
}




#Reward Calculation#
#A function for determining agents' reward given their states and actions
rewardUpdate<-function(agents,q,hhStates,actionResults,foragingVariables){
  
  #Create a dataframe reflecting the new household states
  newStates<-hhStates
  
  #Create a dataframe reflecting observations of the agents' outcomes (for social learning)
  observations<-actionResults
  
  #Add agent gamete size, household state, and reward columns to observations
  observations$gameteSize<-agents$gameteSizeGene1[match(observations$agentID,agents$ID)]
  observations$hhState<-agents$hhState[match(observations$agentID,agents$ID)]
  observations$reward<-0
  
  #Rearrange
  observations<-observations[,c(1:2,7:8,3:6,9)]
  
  #Loop through action results and update household states based on results
  for(a in 1:nrow(agents)){
    
    #Determine new household states
    newStates[newStates$hh==agents$hh[a],
          ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)]=="parent",2,
                 ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),
                        3,4))]<-newStates[newStates$hh==agents$hh[a],
          ifelse(actionResults$action[match(agents$ID[a], actionResults$agentID)]=="parent",2,
                 ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),3,4))] + 
      actionResults$yield[match(agents$ID[a],actionResults$agentID)]
    
    #Determine what resource the agent's action generated
    actionResource<-ifelse(actionResults$action[match(agents$ID[a],actionResults$agentID)]=="parent",1,
                           ifelse(grepl("meat.",actionResults$action[match(agents$ID[a],actionResults$agentID)]),2,3))
    
    #Calculate the reward this action should generate
    #Actions that generate any resource other than the one the household has the least of  results in decreased reward
    agentReward<-ifelse(actionResource==agents$hhState[agents$ID==actionResults$agentID[a]],
                        actionResults$yield[match(agents$ID[a],actionResults$agentID)],
                        actionResults$yield[match(agents$ID[a],actionResults$agentID)]*.25)
    
    #Update observations with reward
    observations$reward[match(agents$ID[a],observations$agentID)]<-agentReward
    

    #Update agents' total rewards
    agents$reward[a]<-agents$reward[a]+agentReward
    
    #Update agents' action history
    agents[a,as.character(paste0(actionResults$action[match(agents$ID[a],actionResults$agentID)],"Hist"))]<-agents[a,as.character(paste0(actionResults$action[match(agents$ID[a],actionResults$agentID)],"Hist"))]+1
    
    #Determine the action-value estimates for the current state-action pair and the best state-action pair in the new state
    currentStateQ<-q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]]
    newStateQ<-max(q[[as.character(agents$ID[a])]][[resample(which(newStates[newStates$hh == agents$hh[a], -1] == max(newStates[newStates$hh == agents$hh[a], -1])), 1)]][, actionResults$newState[match(agents$ID[a], actionResults$agentID)]])
    
    #Implements action-value update using Q-learning
    q[[as.character(agents$ID[a])]][[agents$hhState[a]]][actionResults$action[match(agents$ID[a], actionResults$agentID)], agents$state[a]] <-
      currentStateQ + learningRate * (agentReward + (discount*newStateQ - currentStateQ))
  }
  
  #Update household states
  hhStates<-newStates
  
  return(list(agents,q,hhStates,observations))
}


```



```{r modelStart}

#Loop through model loops
for (p in populations) {
  
  for (e in environments) {
    
    ###Environment Setup###
    
    #Set up environment
    env<-environmentSetup(e)
    
    foragingVariables<-env[[1]]
    tMatrices<-env[[2]]
    
    
    
    ###Population Generation###
    
    #Generate the population
    popGen <- agentGenerate(p, actions, states)
    
    #Extract agents themselves
    agents <- popGen[[1]]
    
    #Extract initial action value functions
    q <- popGen[[2]]
    
    #Determine starting population size
    popSize <- nrow(agents)
    
    #Loop through generations
    for (g in 1:generations) {
      
      #Mating:
      
      #Randomly pair each agent with an opposite-sex partner
      agents$mID <- NA
      
      #Pair agents with opposite sex partners
      if(sum(agents$gameteSizeGene1>3) > sum(agents$gameteSizeGene1<3)){
        agents$mID[agents$gameteSizeGene1 < 3] <- sample(agents$ID[agents$gameteSizeGene1 > 3], nrow(agents[agents$gameteSizeGene1 < 3, ]))
      } else {
        agents$mID[agents$gameteSizeGene1 > 3] <- sample(agents$ID[agents$gameteSizeGene1 < 3], nrow(agents[agents$gameteSizeGene1 > 3, ]))

      }
      
      #Update mate IDs
      agents$mID <- ifelse(is.na(agents$mID) == 1, agents$ID[match(agents$ID, agents$mID)], agents$mID)
      
      #Remove agents who fail to pair
      agents <- agents[!is.na(agents$mID), ]
      
      #And remove their action value functions
      q <- q[names(q) %in% agents$ID]
      
      
      #Household states:
      
      #Assign each agent a household ID which is just the lower of the two mated agents' IDs
      agents$hh <- pmin(agents$ID, agents$mID)
      
      #Create a variable to store current status of household resources
      #Starts with all but parenting set at 1 for simplicity
      hhStates <- data.frame(
        "hh" = unique(agents$hh),
        "parenting" = 0,
        "nutrientM" = 1,
        "nutrientP" = 1
      )
      
      #Give all agents a random starting state
      agents$state <- sample(states, nrow(agents), replace = T)
      agents$hhState <- sapply(agents$hh, function(x)
        resample(which(hhStates[hhStates$hh == x, -1] == min(hhStates[hhStates$hh == x, -1])), 1))
      
      #Loop through days of agents' lives
      for (l in 1:lifeSpan) {
        #Choose an action following epsilon-greedy policy
        chosenActions <- actionSelection(agents, q)
        
        #Determine the state transitions and resource yield of those actions
        actionResults <- transitions(agents, chosenActions, tMatrices)
        
        #Update reward, action values, and household states
        reward <- rewardUpdate(agents, q, hhStates, actionResults, foragingVariables)
        
        #Update agents based on these reward updates
        agents <- reward[[1]]
        
        #And action value functions based on whether agents learn or not
        q <- reward[[2]]
        
        #And household states
        hhStates <- reward[[3]]
        
        #Update agent states
        agents$state <- actionResults$newState[match(agents$ID, actionResults$agentID)]
        
        #And update household states
        agents$hhState <- sapply(agents$hh, function(x)
          resample(which(hhStates[hhStates$hh == x, -1] == min(hhStates[hhStates$hh ==
                                                                          x, -1])), 1))
      }
      
    }
    
    agents$environment<-e
    
    #Create a unique filename and filepath
    path <- "model-outputs/foraging/learning-sex-diffs/MSAG Foraging SDL Population "
    
    format <- ".csv"
    date <- format(Sys.time(), format = "%Y%m%d %H%M")
    file <- file.path(paste0(path, e," ", date, format))
    
    #Save model data
    write.csv(agents, file = file, row.names = F)
    
  }
  
}

```
