```{r packages}

```



```{r parameters}

#The number of agent populations (determined by prior simulation)
populations<-length(list.files("model-outputs/sex-diffs-evolution/",full.names=T))



#Number of generations
generations<-50



#Minimum resources for offspring viability (no longer used here but carried over for parameterization)
resourceThreshold<-5



#Total resources agents will have for producing gametes
resources<-resourceThreshold*20



#Maximum number of gametes an agent will be allowed to produce
maxGametes<-100



#Scales the likelihood of dying as a function of investment in competition in reproductive opportunities
#Max investors will have p = investCompetitionCost probability of dying before gamete production
investCompetitionCost<-(.33)



#Scales the benefit of investment in competition to mating success
#Max investers will have their mate quality increased by investCompetitionBenefit
investCompetitionBenefit<-.33



#Mutation rate
mutationRate<-.05



#Relative selection on parental investment
#Degree to which parental investment vs. mate value determines RS
#Higher values means more selection on parental investment
selectionPI<-c(.3,.8)



#Number of rounds over which mate choice will take place
mateChoiceRounds<-10



#The maximum number of mating opportunities an agent can pursue in a given mating round
maxMates<-100



#Number of pursuit opportunities agents will have within each mating round
nPursuits<-50

```



```{r functions}

#Agent Generation#
#Generate the agents
agentGenerate <- function(population) {
  
  #Load the agents
  agents<-read.csv(list.files("model-outputs/sex-diffs-evolution/",full.names=T)[population])
  
  #Limit to just the final generation of agents
  agents<-agents[agents$generation==max(agents$generation),]
  
  #Remove modelLoop and generation columns for now
  agents<-agents[,-(1:2)]
  
  #Relabel rows
  row.names(agents)<-1:nrow(agents)
  
  #Add a trait reflecting mating-parenting tradeoff, a mate preference, and corresponding trait
  agents$mpTradeoffGene1<-runif(nrow(agents),0,1)
  agents$prefGene1<-rnorm(nrow(agents),.7,mutationRate)
  agents$traitGene1<-rnorm(nrow(agents),.7,mutationRate)
  
  agents$mpTradeoffGene2<-runif(nrow(agents),0,1)
  agents$prefGene2<-rnorm(nrow(agents),.7,mutationRate)
  agents$traitGene2<-rnorm(nrow(agents),.7,mutationRate)
  
  #Rearrange
  agents<-agents[,c(1:5,10:12,6:9,13:15)]
  
  #Output agents
  return(agents)
}




#Mate Choice#
#A function to simulate RWTS mate choice among agents
mateChoice <- function(agents) {
  
  #Create an investment matrix
  invest <- matrix(1, nrow(agents), nrow(agents))
  
  #Create a reciprocity matrix
  recip <- matrix(1, nrow(agents), nrow(agents))

  #Create a matrix of each agent's value to each other agent
  mvMatrix <- matrix(sapply(agents$prefGene1,function(x) 1-abs(agents$traitGene1-x)), nrow(agents), nrow(agents), byrow =
                       T)
  
  #Add MV to agents who invested in mate competition
  mvMatrix<-mvMatrix+matrix(agents$investCompetitionGene1 * investCompetitionBenefit, nrow(agents),nrow(agents),byrow=T)

  #Blank out values of same "sex" agents
  mvMatrix <- t(sapply(1:nrow(agents), function(x)
    mvMatrix[x, ] <- ifelse((agents$gameteSizeGene1[x] < 3 &
                               agents$gameteSizeGene1 < 3) |
                              (agents$gameteSizeGene1[x] > 3 &
                                 agents$gameteSizeGene1 > 3),
                            NA,
                            mvMatrix[x, ]
    )))
  
  #Loop through pursuits
  for (o in 1:nPursuits) {
    #Compute reward matrix
    rewardMatrix <- mvMatrix * recip
    
    #Identify agent choices
    choiceMatrix <- cbind(1:nrow(agents), t(apply(rewardMatrix, 1, function(x)
      order(x, decreasing = T)[1:maxMates])))
    
    #Remove choices beyond the agent's pursuit number
    choiceMatrix[, -1] <- t(sapply(1:nrow(choiceMatrix), function(x)
      c(choiceMatrix[x, (1:agents$pursuits[x]) + 1], rep(
        NA, (maxMates - agents$pursuits[x])
      ))))
    
    #Prevent choices with unmatchable partners
    choiceMatrix[, -1] <- t(sapply(1:nrow(choiceMatrix), function(x)
      ifelse(is.na(rewardMatrix[x, choiceMatrix[x, -1]]), NA, choiceMatrix[x, -1])))
    
    #Update invest matrix based on choices
    for (u in 1:maxMates) {
      invest[choiceMatrix[complete.cases(choiceMatrix[, u + 1]), c(1, u + 1)]] <-
        invest[choiceMatrix[complete.cases(choiceMatrix[, u + 1]), c(1, u + 1)]] +
        1
    }
    
    #Update reciprocity matrix
    recip <- t(invest) / (t(invest) + invest)
    
  }
  
  
  #Determine final choice matrix
  choiceMatrix <- cbind(1:nrow(agents), t(apply(invest, 1, function(x)
    order(x, decreasing = T)[1:maxMates])))
  
  #Remove choices beyond the agent's pursuit number
  choiceMatrix[, -1] <- t(sapply(1:nrow(choiceMatrix), function(x)
    c(choiceMatrix[x, (1:agents$pursuits[x]) + 1], rep(
      NA, (maxMates - agents$pursuits[x])
    ))))
  
  #Prevent choices with invalid partners
  choiceMatrix[, -1] <- t(sapply(1:nrow(choiceMatrix), function(x)
    ifelse(is.na(rewardMatrix[x, choiceMatrix[x, -1]]), NA, choiceMatrix[x, -1])))
  
  #Limit to mutual mate choices
  choiceMatrix[, -1] <- t(sapply(1:nrow(choiceMatrix), function(x)
    sapply(2:ncol(choiceMatrix), function(y)
      ifelse(!(x %in% choiceMatrix[choiceMatrix[x, y], ]), NA, choiceMatrix[x, y]))))
  
  #Convert indexes to IDs
  choiceMatrix<-apply(choiceMatrix,2,function(x) agents$ID[x])
  
  #Remove agents who failed to pair at all
  choiceMatrix <- choiceMatrix[rowMeans(is.na(choiceMatrix[, -1])) < 1, ]
  
  #Reshape matrix
  choiceMatrix <- cbind(rep(choiceMatrix[, 1], each =
                                                maxMates),
                        c(t(choiceMatrix[, -1])))
  
  #Remove NAs
  choiceMatrix <- choiceMatrix[complete.cases(choiceMatrix), ]
  
  #Reorder columns so that agent1 is always the agent with the lower ID
  choiceMatrix <- t(apply(choiceMatrix, 1, function(x)
    sort(x)))
  
  #Remove duplicate entries of each agent couple
  choiceMatrix <- choiceMatrix[!duplicated(choiceMatrix), ]
  
  #Convert to dataframe
  choiceMatrix<-data.frame(choiceMatrix)
  
  #Relabel columns
  colnames(choiceMatrix)<-c("agent1ID","agent2ID")
  
  #Output the matrix of agent choices
  return(choiceMatrix)
}



#Reproduce#
#Produce offspring from parents
reproduce <- function(agents, mateChoices, selectionPI) {
  
  #Determine how many gametes agents have to dedicate to each pairing
  mateChoices$p1NumGametes<-agents$gametes[match(mateChoices$agent1ID,agents$ID)]/
    sapply(mateChoices$agent1ID,function(x) sum(x==c(mateChoices$agent1ID,mateChoices$agent2ID)))
  mateChoices$p2NumGametes<-agents$gametes[match(mateChoices$agent2ID,agents$ID)]/
    sapply(mateChoices$agent2ID,function(x) sum(x==c(mateChoices$agent1ID,mateChoices$agent2ID)))
  
  #For agents with fewer gametes than mates, determine which mating opportunities get gametes probabilistically
  mateChoices$p1NumGametes[mateChoices$p1NumGametes<1]<-rbinom(length(mateChoices$p1NumGametes[mateChoices$p1NumGametes<1]),
                                                               1,
                                                               mateChoices$p1NumGametes[mateChoices$p1NumGametes<1])
  mateChoices$p2NumGametes[mateChoices$p2NumGametes<1]<-rbinom(length(mateChoices$p2NumGametes[mateChoices$p2NumGametes<1]),
                                                               1,
                                                               mateChoices$p2NumGametes[mateChoices$p2NumGametes<1])
  
  #Remove any pairings where either agent had 0 gametes
  mateChoices<-mateChoices[mateChoices[,3]>0 & mateChoices[,4] > 0,]
  
  #Add in parent MVs
  mateChoices$p1Mv<-1-abs(agents$traitGene1[match(mateChoices$agent1ID,agents$ID)]-.7)
  mateChoices$p2Mv<-1-abs(agents$traitGene1[match(mateChoices$agent2ID,agents$ID)]-.7)
  
  #Add in investment
  mateChoices$p1Investment<-(1-agents$mpTradeoffGene1[match(mateChoices$agent1ID,agents$ID)])
  mateChoices$p2Investment<-(1-agents$mpTradeoffGene1[match(mateChoices$agent2ID,agents$ID)])
  
  #Calculate overall parent MVs and investment
  mateChoices$mv<-as.numeric(scale(mateChoices$p1Mv+mateChoices$p2Mv))
  mateChoices$investment<-as.numeric(scale(mateChoices$p1Investment+mateChoices$p2Investment))

  #Compute into a noisy weight to determine which parents produce offspring
  mateChoices$pOffspring <-(1 - selectionPI) * (mateChoices$mv + rnorm(nrow(mateChoices),0,sd(mateChoices$mv))) +
    (selectionPI) * mateChoices$investment
  
  #Sort by reproduction weight
  mateChoices<-mateChoices[order(mateChoices$pOffspring,decreasing=T),]
  
  #Select the agents that get to reproduce
  parents<-mateChoices[1:min(c(nrow(mateChoices),floor(1.2*popSize/mateChoiceRounds))),]
  
  #Create a blank dataframe for storing offspring
  offspring<-agents[0,c(1,1:15)]
  
  #Rearrange and relabel
  colnames(offspring)[1:2]<-c("parent1ID","parent2ID")
  
  #Loop through parents dataframe to create offspring
  for(r in 1:nrow(parents)){
    
    parent1<-agents[agents$ID==parents$agent1ID[r],]
    parent2<-agents[agents$ID==parents$agent2ID[r],]
    
    #Determine which parents' genes will be expressed
    expressedParent<-sample(1:2,1)
    
    #Determine for both parents which of their genes will be inherited
    expressedGenes<-sample(1:2,2,replace=T)
    
    #Create the offspring using the randomly determined genes
    if(expressedParent==1){
      child<-cbind(parent1$ID,parent2$ID,
                   if(expressedGenes[1]==1){parent1[,c(2:8)]} else{parent1[,c(9:15)]},
                   if(expressedGenes[2]==1){parent2[,c(2:8)]} else{parent2[,c(9:15)]})
    } else {
      child<-cbind(parent2$ID,parent1$ID,
             if(expressedGenes[1]==1){parent2[,c(2:8)]} else{parent2[,c(9:15)]},
             if(expressedGenes[2]==1){parent1[,c(2:8)]} else{parent1[,c(9:15)]})

    }
    
    #Relabel columns
    colnames(child)<-colnames(offspring)
    
    #Add the child to the offspring dataframe
    offspring<-rbind(offspring,child)
  }
  
  #Add mutation to relevant genes
  offspring[,c(7:9,14:16)]<-offspring[,c(7:9,14:16)]+rnorm(nrow(offspring)*6,0,mutationRate)
  
  #Prevent trait values out of bounds
  offspring[,c(7:9,14:16)]<-apply(offspring[c(7:9,14:16)],2, function(x)
      ifelse(x>1, 1, ifelse(x<0, 0, x)))
  
  #Output the offspring
  return(offspring)
  
}


```



```{r modelStart}

#Loop through model loops
for (p in 1:populations) {
  
  for (s in selectionPI) {
    
    #Load in the agent population
    agents <- agentGenerate(p)
    
    #Determine starting population size
    popSize <- nrow(agents)
    
    #Create a dataframe to store agents
    data <- cbind(
      "modelLoop" = p,
      "generation" = 0,
      "selectionPI" = s,
      agents
    )
    
    #Loop through generations
    for (g in 1:generations) {

      #Pre-reproductive mortality
      #Some agents die before getting to reproduce by virtue of their investment in mate competition
      agents <- agents[which(rbinom(
        nrow(agents),
        1,
        1 - (agents$investCompetitionGene1 * investCompetitionCost)
      ) == 1), ]
      
      
      #Reduce agent resources according to investment in parenting
      #Agents have their gamete budget reduced to the extent that they invested in parenting
      agents$resources <- resources * (1 - (agents$investParentingGene1))
      
      
      #Determine how many gametes each agent produces
      agents$gametes <- floor(agents$resources / agents$gameteSizeGene1)
      
      
      #Determine the number of mates each agent will pursue each round
      #1 is added to prevent agents who cannot mate at all; 1 is subtracted from maxMates to compensate
      agents$pursuits <- ceiling(agents$mpTradeoffGene1 * (maxMates - 1)) + 1
      
      
      #Loop through rounds of mate choice
      for (m in 1:mateChoiceRounds) {
        
        mateChoices <- mateChoice(agents)
        
        if (m == 1) {
          offspring <- reproduce(agents, mateChoices, s)
        } else{
          offspring <- rbind(offspring, reproduce(agents, mateChoices, s))
        }
        
      }
      
      
      #Post-reproductive mortality
      #Agents increase the likelihood of their offspring surviving to the extent that they invest in parenting
      #This parenting is divided evenly among all of an agent's offspring
      postReproMortalityRisk <- agents$investParentingGene1[match(offspring$parent1ID, agents$ID)] /
        sapply(offspring$parent1ID, function(x)
          sum(c(
            offspring$parent1ID == x, offspring$parent2ID == x
          ))) +
        agents$investParentingGene1[match(offspring$parent2ID, agents$ID)] /
        sapply(offspring$parent2ID, function(x)
          sum(c(
            offspring$parent1ID == x, offspring$parent2ID == x
          )))
      
      #Sort offspring by parents' investment in parenting
      offspring <- offspring[order(postReproMortalityRisk, decreasing = T), ]
      
      #Select the top popSize agents by parental investment to survive
      offspring <- offspring[1:min(c(nrow(offspring), popSize)), ]
      
      #Overwrite parents with offspring
      agents <- offspring[sample(1:nrow(offspring)), ]
      
      #Remove the first parentID column
      agents <- agents[, -1]
      
      #Rename it
      colnames(agents)[1] <- "ID"
      
      #Assign new IDs
      agents$ID <- 1:nrow(agents)
      
      #Save agents to overall data frame
      data <- rbind(data,
                    cbind(
                      "modelLoop" = p,
                      "generation" = g,
                      "selectionPI" = s,
                      agents
                    ))
      
    }
    
    #Create a unique filename and filepath
    path <- "model-outputs/mating-strategy/MSAG Mating Strategy Evolution Population "
    
    format <- ".csv"
    date <- format(Sys.time(), format = "%Y%m%d %H%M")
    file <- file.path(paste0(path, p, ifelse(s == min(selectionPI), " PI LO ", " PI HI "), date, format))
    
    #Save model data
    write.csv(data, file = file, row.names = F)
  }
}
  
  

```
